#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif

#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>
#include <stdlib.h>
#include <string.h>


/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyLong_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyLong_FromLong((long)x) :                                   \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyLong_FromLong((long)x) :                                   \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFCx specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.11.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'language': 'C',
//   'part': 'full',
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle

void tabulate_tensor_integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    void* custom_data)
{
// Quadrature rules
static const double weights_1ec[12] = {0.0254224531851035, 0.0254224531851035, 0.0254224531851035, 0.0583931378631895, 0.0583931378631895, 0.0583931378631895, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_D100_F_Q1ec[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
static const double FE1_C1_D010_F_Q1ec[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
static const double FE1_C2_D001_F_Q1ec[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
static const double FE4_C0_F_Q1ec[1][4][12][10] = {{{{0.0, -0.05512856699248415, 0.6533077030470594, -0.05512856699248408, 0.2205142679699366, 0.01592089499803585, 0.2205142679699364, 0.0, 0.0, 0.0},
  {0.0, -0.05512856699248409, -0.05512856699248413, 0.6533077030470597, 0.2205142679699365, 0.2205142679699364, 0.01592089499803572, 0.0, 0.0, 0.0},
  {0.0, 0.6533077030470595, -0.05512856699248414, -0.05512856699248408, 0.0159208949980358, 0.2205142679699365, 0.2205142679699364, 0.0, 0.0, 0.0},
  {0.0, -0.1249989825350976, 0.001430579517788743, -0.1249989825350976, 0.4999959301403893, 0.248575525271626, 0.4999959301403913, 0.0, 0.0, 0.0},
  {0.0, -0.1249989825350976, -0.1249989825350976, 0.001430579517788831, 0.4999959301403894, 0.4999959301403914, 0.2485755252716258, 0.0, 0.0, 0.0},
  {0.0, 0.001430579517789739, -0.1249989825350976, -0.1249989825350975, 0.248575525271625, 0.4999959301403904, 0.4999959301403902, 0.0, 0.0, 0.0},
  {0.0, -0.0474962571988001, 0.1737683636541741, -0.1177151633084292, 0.7901604427658231, 0.06597478591860542, 0.1353078281686269, 0.0, 0.0, 0.0},
  {0.0, -0.1177151633084292, 0.1737683636541741, -0.04749625719880005, 0.1353078281686269, 0.06597478591860528, 0.7901604427658231, 0.0, 0.0, 0.0},
  {0.0, -0.04749625719880009, -0.1177151633084292, 0.1737683636541741, 0.7901604427658232, 0.135307828168627, 0.0659747859186053, 0.0, 0.0, 0.0},
  {0.0, 0.173768363654174, -0.1177151633084292, -0.04749625719880005, 0.06597478591860531, 0.1353078281686268, 0.790160442765823, 0.0, 0.0, 0.0},
  {0.0, -0.1177151633084292, -0.04749625719880007, 0.1737683636541742, 0.1353078281686269, 0.7901604427658233, 0.06597478591860521, 0.0, 0.0, 0.0},
  {0.0, 0.1737683636541741, -0.04749625719880007, -0.1177151633084291, 0.06597478591860541, 0.7901604427658232, 0.1353078281686267, 0.0, 0.0, 0.0}},
  {{-0.05512856699248415, 0.0, 0.6533077030470594, -0.05512856699248408, 0.2205142679699366, 0.0, 0.0, 0.01592089499803579, 0.2205142679699365, 0.0},
  {-0.05512856699248406, 0.0, -0.05512856699248411, 0.6533077030470597, 0.2205142679699364, 0.0, 0.0, 0.2205142679699363, 0.01592089499803574, 0.0},
  {0.6533077030470598, 0.0, -0.0551285669924841, -0.0551285669924841, 0.01592089499803585, 0.0, 0.0, 0.2205142679699364, 0.2205142679699364, 0.0},
  {-0.1249989825350976, 0.0, 0.001430579517788806, -0.1249989825350976, 0.4999959301403893, 0.0, 0.0, 0.2485755252716258, 0.4999959301403912, 0.0},
  {-0.1249989825350975, 0.0, -0.1249989825350975, 0.001430579517788776, 0.4999959301403892, 0.0, 0.0, 0.4999959301403911, 0.2485755252716258, 0.0},
  {0.001430579517789795, 0.0, -0.1249989825350975, -0.1249989825350976, 0.2485755252716248, 0.0, 0.0, 0.4999959301403902, 0.4999959301403902, 0.0},
  {-0.0474962571988001, 0.0, 0.1737683636541741, -0.1177151633084292, 0.7901604427658231, 0.0, 0.0, 0.06597478591860532, 0.1353078281686269, 0.0},
  {-0.1177151633084292, 0.0, 0.1737683636541741, -0.04749625719880005, 0.1353078281686269, 0.0, 0.0, 0.06597478591860523, 0.7901604427658231, 0.0},
  {-0.04749625719880005, 0.0, -0.1177151633084292, 0.1737683636541741, 0.7901604427658232, 0.0, 0.0, 0.1353078281686269, 0.0659747859186053, 0.0},
  {0.173768363654174, 0.0, -0.1177151633084291, -0.04749625719880005, 0.06597478591860537, 0.0, 0.0, 0.1353078281686267, 0.7901604427658231, 0.0},
  {-0.1177151633084292, 0.0, -0.0474962571988, 0.1737683636541741, 0.1353078281686266, 0.0, 0.0, 0.7901604427658231, 0.06597478591860523, 0.0},
  {0.1737683636541741, 0.0, -0.0474962571988, -0.1177151633084292, 0.06597478591860513, 0.0, 0.0, 0.7901604427658228, 0.1353078281686268, 0.0}},
  {{-0.05512856699248416, 0.6533077030470595, 0.0, -0.05512856699248407, 0.0, 0.2205142679699366, 0.0, 0.01592089499803584, 0.0, 0.2205142679699366},
  {-0.0551285669924841, -0.05512856699248411, 0.0, 0.6533077030470597, 0.0, 0.2205142679699365, 0.0, 0.2205142679699365, 0.0, 0.01592089499803577},
  {0.6533077030470598, -0.05512856699248404, 0.0, -0.0551285669924841, 0.0, 0.01592089499803586, 0.0, 0.2205142679699365, 0.0, 0.2205142679699362},
  {-0.1249989825350976, 0.001430579517788756, 0.0, -0.1249989825350976, 0.0, 0.4999959301403895, 0.0, 0.248575525271626, 0.0, 0.4999959301403914},
  {-0.1249989825350976, -0.1249989825350976, 0.0, 0.001430579517788802, 0.0, 0.4999959301403894, 0.0, 0.4999959301403912, 0.0, 0.2485755252716259},
  {0.001430579517789784, -0.1249989825350976, 0.0, -0.1249989825350976, 0.0, 0.2485755252716249, 0.0, 0.4999959301403904, 0.0, 0.4999959301403904},
  {-0.04749625719880014, 0.173768363654174, 0.0, -0.1177151633084291, 0.0, 0.7901604427658232, 0.0, 0.06597478591860542, 0.0, 0.1353078281686269},
  {-0.1177151633084292, 0.1737683636541741, 0.0, -0.04749625719880004, 0.0, 0.135307828168627, 0.0, 0.06597478591860548, 0.0, 0.7901604427658231},
  {-0.04749625719880009, -0.1177151633084292, 0.0, 0.1737683636541742, 0.0, 0.7901604427658232, 0.0, 0.135307828168627, 0.0, 0.06597478591860524},
  {0.1737683636541741, -0.1177151633084292, 0.0, -0.04749625719880005, 0.0, 0.06597478591860552, 0.0, 0.135307828168627, 0.0, 0.7901604427658231},
  {-0.1177151633084291, -0.04749625719880005, 0.0, 0.1737683636541741, 0.0, 0.1353078281686267, 0.0, 0.7901604427658229, 0.0, 0.06597478591860534},
  {0.1737683636541741, -0.04749625719880009, 0.0, -0.1177151633084292, 0.0, 0.06597478591860516, 0.0, 0.790160442765823, 0.0, 0.1353078281686269}},
  {{-0.05512856699248419, 0.6533077030470594, -0.05512856699248411, 0.0, 0.0, 0.0, 0.2205142679699366, 0.0, 0.01592089499803589, 0.2205142679699366},
  {-0.05512856699248407, -0.05512856699248407, 0.6533077030470595, 0.0, 0.0, 0.0, 0.2205142679699364, 0.0, 0.2205142679699364, 0.01592089499803585},
  {0.6533077030470598, -0.0551285669924841, -0.05512856699248412, 0.0, 0.0, 0.0, 0.01592089499803595, 0.0, 0.2205142679699366, 0.2205142679699362},
  {-0.1249989825350976, 0.001430579517788742, -0.1249989825350976, 0.0, 0.0, 0.0, 0.4999959301403893, 0.0, 0.248575525271626, 0.4999959301403913},
  {-0.1249989825350976, -0.1249989825350976, 0.001430579517788755, 0.0, 0.0, 0.0, 0.4999959301403894, 0.0, 0.4999959301403912, 0.2485755252716259},
  {0.001430579517789742, -0.1249989825350976, -0.1249989825350976, 0.0, 0.0, 0.0, 0.2485755252716251, 0.0, 0.4999959301403903, 0.4999959301403903},
  {-0.04749625719880009, 0.1737683636541739, -0.1177151633084292, 0.0, 0.0, 0.0, 0.7901604427658232, 0.0, 0.06597478591860538, 0.1353078281686269},
  {-0.1177151633084292, 0.1737683636541741, -0.04749625719880005, 0.0, 0.0, 0.0, 0.135307828168627, 0.0, 0.06597478591860544, 0.7901604427658232},
  {-0.04749625719880009, -0.1177151633084292, 0.173768363654174, 0.0, 0.0, 0.0, 0.7901604427658232, 0.0, 0.1353078281686269, 0.06597478591860532},
  {0.1737683636541741, -0.1177151633084292, -0.04749625719880003, 0.0, 0.0, 0.0, 0.06597478591860545, 0.0, 0.135307828168627, 0.7901604427658232},
  {-0.1177151633084292, -0.04749625719880012, 0.1737683636541741, 0.0, 0.0, 0.0, 0.135307828168627, 0.0, 0.790160442765823, 0.06597478591860528},
  {0.1737683636541739, -0.04749625719880012, -0.1177151633084291, 0.0, 0.0, 0.0, 0.06597478591860541, 0.0, 0.7901604427658232, 0.1353078281686269}}}};
static const double tetrahedron_cell_facet_jacobian[4][3][2] = {{{-1.0, -1.0},
  {1.0, 0.0},
  {0.0, 1.0}},
  {{0.0, 0.0},
  {1.0, 0.0},
  {0.0, 1.0}},
  {{1.0, 0.0},
  {0.0, 0.0},
  {0.0, 1.0}},
  {{1.0, 0.0},
  {0.0, 1.0},
  {0.0, 0.0}}};
static const double tetrahedron_reference_normals[4][3] = {{0.5773502691896258, 0.5773502691896258, 0.5773502691896258},
  {-1.0, -0.0, -0.0},
  {0.0, -1.0, 0.0},
  {-0.0, -0.0, -1.0}};
// ------------------------ 
// Section: Jacobian
// Inputs: FE1_C0_D100_F_Q1ec, FE1_C1_D010_F_Q1ec, coordinate_dofs, FE1_C2_D001_F_Q1ec
// Outputs: J0_c3, J0_c6, J0_c2, J0_c5, J0_c4, J0_c8, J0_c0, J0_c1, J0_c7
double J0_c4 = 0.0;
double J0_c8 = 0.0;
double J0_c5 = 0.0;
double J0_c7 = 0.0;
double J0_c0 = 0.0;
double J0_c3 = 0.0;
double J0_c6 = 0.0;
double J0_c1 = 0.0;
double J0_c2 = 0.0;
{
  for (int ic = 0; ic < 4; ++ic)
  {
    J0_c4 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D010_F_Q1ec[0][0][0][ic];
    J0_c8 += coordinate_dofs[(ic) * 3 + 2] * FE1_C2_D001_F_Q1ec[0][0][0][ic];
    J0_c5 += coordinate_dofs[(ic) * 3 + 1] * FE1_C2_D001_F_Q1ec[0][0][0][ic];
    J0_c7 += coordinate_dofs[(ic) * 3 + 2] * FE1_C1_D010_F_Q1ec[0][0][0][ic];
    J0_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D100_F_Q1ec[0][0][0][ic];
    J0_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D100_F_Q1ec[0][0][0][ic];
    J0_c6 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D100_F_Q1ec[0][0][0][ic];
    J0_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D010_F_Q1ec[0][0][0][ic];
    J0_c2 += coordinate_dofs[(ic) * 3] * FE1_C2_D001_F_Q1ec[0][0][0][ic];
  }
}
// ------------------------ 
double sp_1ec_0 = J0_c4 * J0_c8;
double sp_1ec_1 = J0_c5 * J0_c7;
double sp_1ec_2 = -sp_1ec_1;
double sp_1ec_3 = sp_1ec_0 + sp_1ec_2;
double sp_1ec_4 = J0_c0 * sp_1ec_3;
double sp_1ec_5 = J0_c3 * J0_c8;
double sp_1ec_6 = J0_c5 * J0_c6;
double sp_1ec_7 = -sp_1ec_6;
double sp_1ec_8 = sp_1ec_5 + sp_1ec_7;
double sp_1ec_9 = -J0_c1;
double sp_1ec_10 = sp_1ec_8 * sp_1ec_9;
double sp_1ec_11 = sp_1ec_4 + sp_1ec_10;
double sp_1ec_12 = J0_c3 * J0_c7;
double sp_1ec_13 = J0_c4 * J0_c6;
double sp_1ec_14 = -sp_1ec_13;
double sp_1ec_15 = sp_1ec_12 + sp_1ec_14;
double sp_1ec_16 = J0_c2 * sp_1ec_15;
double sp_1ec_17 = sp_1ec_11 + sp_1ec_16;
double sp_1ec_18 = sp_1ec_3 / sp_1ec_17;
double sp_1ec_19 = tetrahedron_reference_normals[entity_local_index[0]][0] * sp_1ec_18;
double sp_1ec_20 = -J0_c8;
double sp_1ec_21 = J0_c3 * sp_1ec_20;
double sp_1ec_22 = sp_1ec_6 + sp_1ec_21;
double sp_1ec_23 = sp_1ec_22 / sp_1ec_17;
double sp_1ec_24 = tetrahedron_reference_normals[entity_local_index[0]][1] * sp_1ec_23;
double sp_1ec_25 = sp_1ec_19 + sp_1ec_24;
double sp_1ec_26 = sp_1ec_15 / sp_1ec_17;
double sp_1ec_27 = tetrahedron_reference_normals[entity_local_index[0]][2] * sp_1ec_26;
double sp_1ec_28 = sp_1ec_25 + sp_1ec_27;
double sp_1ec_29 = sp_1ec_28 * sp_1ec_28;
double sp_1ec_30 = J0_c2 * J0_c7;
double sp_1ec_31 = J0_c8 * sp_1ec_9;
double sp_1ec_32 = sp_1ec_30 + sp_1ec_31;
double sp_1ec_33 = sp_1ec_32 / sp_1ec_17;
double sp_1ec_34 = tetrahedron_reference_normals[entity_local_index[0]][0] * sp_1ec_33;
double sp_1ec_35 = J0_c0 * J0_c8;
double sp_1ec_36 = -J0_c2;
double sp_1ec_37 = J0_c6 * sp_1ec_36;
double sp_1ec_38 = sp_1ec_35 + sp_1ec_37;
double sp_1ec_39 = sp_1ec_38 / sp_1ec_17;
double sp_1ec_40 = tetrahedron_reference_normals[entity_local_index[0]][1] * sp_1ec_39;
double sp_1ec_41 = sp_1ec_34 + sp_1ec_40;
double sp_1ec_42 = J0_c1 * J0_c6;
double sp_1ec_43 = J0_c0 * J0_c7;
double sp_1ec_44 = -sp_1ec_43;
double sp_1ec_45 = sp_1ec_42 + sp_1ec_44;
double sp_1ec_46 = sp_1ec_45 / sp_1ec_17;
double sp_1ec_47 = tetrahedron_reference_normals[entity_local_index[0]][2] * sp_1ec_46;
double sp_1ec_48 = sp_1ec_41 + sp_1ec_47;
double sp_1ec_49 = sp_1ec_48 * sp_1ec_48;
double sp_1ec_50 = sp_1ec_29 + sp_1ec_49;
double sp_1ec_51 = J0_c1 * J0_c5;
double sp_1ec_52 = J0_c2 * J0_c4;
double sp_1ec_53 = -sp_1ec_52;
double sp_1ec_54 = sp_1ec_51 + sp_1ec_53;
double sp_1ec_55 = sp_1ec_54 / sp_1ec_17;
double sp_1ec_56 = tetrahedron_reference_normals[entity_local_index[0]][0] * sp_1ec_55;
double sp_1ec_57 = J0_c2 * J0_c3;
double sp_1ec_58 = J0_c0 * J0_c5;
double sp_1ec_59 = -sp_1ec_58;
double sp_1ec_60 = sp_1ec_57 + sp_1ec_59;
double sp_1ec_61 = sp_1ec_60 / sp_1ec_17;
double sp_1ec_62 = tetrahedron_reference_normals[entity_local_index[0]][1] * sp_1ec_61;
double sp_1ec_63 = sp_1ec_56 + sp_1ec_62;
double sp_1ec_64 = J0_c0 * J0_c4;
double sp_1ec_65 = J0_c1 * J0_c3;
double sp_1ec_66 = -sp_1ec_65;
double sp_1ec_67 = sp_1ec_64 + sp_1ec_66;
double sp_1ec_68 = sp_1ec_67 / sp_1ec_17;
double sp_1ec_69 = tetrahedron_reference_normals[entity_local_index[0]][2] * sp_1ec_68;
double sp_1ec_70 = sp_1ec_63 + sp_1ec_69;
double sp_1ec_71 = sp_1ec_70 * sp_1ec_70;
double sp_1ec_72 = sp_1ec_50 + sp_1ec_71;
double sp_1ec_73 = sqrt(sp_1ec_72);
double sp_1ec_74 = sp_1ec_28 / sp_1ec_73;
double sp_1ec_75 = 0.0003500000002496154 * sp_1ec_74;
double sp_1ec_76 = sp_1ec_48 / sp_1ec_73;
double sp_1ec_77 = 0.0003500000002496154 * sp_1ec_76;
double sp_1ec_78 = sp_1ec_70 / sp_1ec_73;
double sp_1ec_79 = 0.0003500000002496154 * sp_1ec_78;
double sp_1ec_80 = 1.147859789166605e+15 * sp_1ec_75;
double sp_1ec_81 = 1.147859789166605e+15 * sp_1ec_77;
double sp_1ec_82 = 1.147859789166605e+15 * sp_1ec_79;
double sp_1ec_83 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][0] * J0_c3;
double sp_1ec_84 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][0] * J0_c4;
double sp_1ec_85 = sp_1ec_83 + sp_1ec_84;
double sp_1ec_86 = J0_c5 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][0];
double sp_1ec_87 = sp_1ec_85 + sp_1ec_86;
double sp_1ec_88 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][1] * J0_c6;
double sp_1ec_89 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][1] * J0_c7;
double sp_1ec_90 = sp_1ec_88 + sp_1ec_89;
double sp_1ec_91 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][1] * J0_c8;
double sp_1ec_92 = sp_1ec_90 + sp_1ec_91;
double sp_1ec_93 = sp_1ec_87 * sp_1ec_92;
double sp_1ec_94 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][1] * J0_c3;
double sp_1ec_95 = J0_c4 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][1];
double sp_1ec_96 = sp_1ec_94 + sp_1ec_95;
double sp_1ec_97 = J0_c5 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][1];
double sp_1ec_98 = sp_1ec_96 + sp_1ec_97;
double sp_1ec_99 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][0] * J0_c6;
double sp_1ec_100 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][0] * J0_c7;
double sp_1ec_101 = sp_1ec_99 + sp_1ec_100;
double sp_1ec_102 = tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][0] * J0_c8;
double sp_1ec_103 = sp_1ec_101 + sp_1ec_102;
double sp_1ec_104 = sp_1ec_98 * sp_1ec_103;
double sp_1ec_105 = -sp_1ec_104;
double sp_1ec_106 = sp_1ec_93 + sp_1ec_105;
double sp_1ec_107 = sp_1ec_106 * sp_1ec_106;
double sp_1ec_108 = J0_c0 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][1];
double sp_1ec_109 = J0_c1 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][1];
double sp_1ec_110 = sp_1ec_108 + sp_1ec_109;
double sp_1ec_111 = J0_c2 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][1];
double sp_1ec_112 = sp_1ec_110 + sp_1ec_111;
double sp_1ec_113 = sp_1ec_112 * sp_1ec_103;
double sp_1ec_114 = J0_c0 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][0][0];
double sp_1ec_115 = J0_c1 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][1][0];
double sp_1ec_116 = sp_1ec_114 + sp_1ec_115;
double sp_1ec_117 = J0_c2 * tetrahedron_cell_facet_jacobian[entity_local_index[0]][2][0];
double sp_1ec_118 = sp_1ec_116 + sp_1ec_117;
double sp_1ec_119 = sp_1ec_118 * sp_1ec_92;
double sp_1ec_120 = -sp_1ec_119;
double sp_1ec_121 = sp_1ec_113 + sp_1ec_120;
double sp_1ec_122 = sp_1ec_121 * sp_1ec_121;
double sp_1ec_123 = sp_1ec_107 + sp_1ec_122;
double sp_1ec_124 = sp_1ec_118 * sp_1ec_98;
double sp_1ec_125 = sp_1ec_87 * sp_1ec_112;
double sp_1ec_126 = -sp_1ec_125;
double sp_1ec_127 = sp_1ec_124 + sp_1ec_126;
double sp_1ec_128 = sp_1ec_127 * sp_1ec_127;
double sp_1ec_129 = sp_1ec_123 + sp_1ec_128;
double sp_1ec_130 = sqrt(sp_1ec_129);
double sp_1ec_131 = sp_1ec_80 * sp_1ec_130;
double sp_1ec_132 = sp_1ec_81 * sp_1ec_130;
double sp_1ec_133 = sp_1ec_82 * sp_1ec_130;
for (int iq = 0; iq < 12; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0, fw1, fw2
  double fw0 = 0;
  double fw1 = 0;
  double fw2 = 0;
  {
    fw0 = sp_1ec_131 * weights_1ec[iq];
    fw1 = sp_1ec_132 * weights_1ec[iq];
    fw2 = sp_1ec_133 * weights_1ec[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw1, fw2, FE4_C0_F_Q1ec, fw0
  // Outputs: A
  {
    double temp_0[1] = {0};
    for (int j = 0; j < 1; ++j)
    {
      temp_0[j] = fw0 * 1;
    }
    double temp_1[1] = {0};
    for (int j = 0; j < 1; ++j)
    {
      temp_1[j] = fw1 * 1;
    }
    double temp_2[1] = {0};
    for (int j = 0; j < 1; ++j)
    {
      temp_2[j] = fw2 * 1;
    }
    for (int j = 0; j < 1; ++j)
    {
      for (int i = 0; i < 10; ++i)
      {
        A[3 * (i) + (j)] += FE4_C0_F_Q1ec[0][entity_local_index[0]][iq][i] * temp_0[j];
        A[(3 * (i) + 1) + (j)] += FE4_C0_F_Q1ec[0][entity_local_index[0]][iq][i] * temp_1[j];
        A[(3 * (i) + 2) + (j)] += FE4_C0_F_Q1ec[0][entity_local_index[0]][iq][i] * temp_2[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(16933917893659141078),
  .domain = 2,
};

// End of code for integral integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle

// Code for form form_98aa834bf0cdab742e461d18c062de0130fc8d37


uint64_t finite_element_hashes_form_98aa834bf0cdab742e461d18c062de0130fc8d37[2] = {UINT64_C(16933917893659141079), UINT64_C(0)};
int form_integral_offsets_form_98aa834bf0cdab742e461d18c062de0130fc8d37[6] = {0, 0, 1, 1, 1, 1};
static ufcx_integral* form_integrals_form_98aa834bf0cdab742e461d18c062de0130fc8d37[1] = {&integral_4180a5dd95a36e19b3a3998bdcf1d4227e02c853_triangle};
int form_integral_ids_form_98aa834bf0cdab742e461d18c062de0130fc8d37[1] = {4};






ufcx_form form_98aa834bf0cdab742e461d18c062de0130fc8d37 =
{

  .signature = "834a6fda3b8e8a1161f225c8eb91a00edd7710d4db7c0a5bdc4b52425a54258dadf2083fa391a8be3297bd4ec4df8f732632262c0ed2a7df77a02ae246392c0b",
  .rank = 2,

  .num_coefficients = 0,
  .original_coefficient_positions = NULL,
  .coefficient_name_map = NULL,

  .num_constants = 0,
  .constant_ranks = NULL,
  .constant_shapes = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_98aa834bf0cdab742e461d18c062de0130fc8d37,

  .form_integrals = form_integrals_form_98aa834bf0cdab742e461d18c062de0130fc8d37,
  .form_integral_ids = form_integral_ids_form_98aa834bf0cdab742e461d18c062de0130fc8d37,
  .form_integral_offsets = form_integral_offsets_form_98aa834bf0cdab742e461d18c062de0130fc8d37
};

// Alias name
ufcx_form* form_libffcx_forms_497fe53e751c8681fa0ece47877699d27f75c347_0 = &form_98aa834bf0cdab742e461d18c062de0130fc8d37;

// End of code for form form_98aa834bf0cdab742e461d18c062de0130fc8d37


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double const *
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void *
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t *
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t const *
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // _Bool const *
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // _cffi_double_complex_t
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // _cffi_float_complex_t
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const * *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // char const *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int *
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int const * *
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // ufcx_integral * *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufcx_integral *
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 52 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // uint64_t *
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // void(*)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_ridge(unsigned long long *o)
{
  int n = (ridge) <= 0;
  *o = (unsigned long long)((ridge) | 0);  /* check that ridge is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int const * *tmp = &p->constant_ranks; (void)tmp; }
  { int const * * *tmp = &p->constant_shapes; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
  (void)((p->domain) | 0);  /* check that 'ufcx_integral.domain' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_98aa834bf0cdab742e461d18c062de0130fc8d37(void)
{
  return &(form_98aa834bf0cdab742e461d18c062de0130fc8d37);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_98aa834bf0cdab742e461d18c062de0130fc8d37", (void *)_cffi_var_form_98aa834bf0cdab742e461d18c062de0130fc8d37, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 48), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ridge", (void *)_cffi_const_ridge, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "constant_ranks", offsetof(ufcx_form, constant_ranks),
                      sizeof(((ufcx_form *)0)->constant_ranks),
                      _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "constant_shapes", offsetof(ufcx_form, constant_shapes),
                       sizeof(((ufcx_form *)0)->constant_shapes),
                       _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 59) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "domain", offsetof(ufcx_integral, domain),
              sizeof(((ufcx_integral *)0)->domain),
              _CFFI_OP(_CFFI_OP_NOOP, 55) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 48, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 13 },
  { "ufcx_integral", 51, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 13, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 52, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet,vertex,ridge" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 48 },
  { "ufcx_integral", 51 },
  { "ufcx_integral_type", 52 },
  { "ufcx_tabulate_tensor_complex128", 0 },
  { "ufcx_tabulate_tensor_complex64", 9 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 18 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  6,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  61,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_497fe53e751c8681fa0ece47877699d27f75c347(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
    return NULL;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
     PyInit_libffcx_forms_497fe53e751c8681fa0ece47877699d27f75c347(void) { return NULL; }
#  endif
#else
PyMODINIT_FUNC
PyInit_libffcx_forms_497fe53e751c8681fa0ece47877699d27f75c347(void)
{
  return _cffi_init("libffcx_forms_497fe53e751c8681fa0ece47877699d27f75c347", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
