"""SWC validation and serialization; no geometry fitting or filtering."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import networkx as nx
import numpy as np


@dataclass
class Source:
    path: Path
    rows: np.ndarray
    graph: nx.DiGraph


def read_source(path: Path, *, allow_forest: bool = False) -> Source:
    rows = np.loadtxt(path, comments="#", ndmin=2)
    if rows.shape[1] != 7 or len(rows) < 2:
        raise ValueError("SWC requires seven columns and at least two nodes")
    if not np.isfinite(rows).all():
        raise ValueError("Nonfinite SWC coordinate, radius or identifier")
    if not np.equal(rows[:, [0, 1, 6]], np.floor(rows[:, [0, 1, 6]])).all():
        raise ValueError("SWC ID, TYPE and PARENT must be integers")
    ids = rows[:, 0].astype(np.int64)
    if len(set(ids)) != len(ids) or np.any(ids < 0):
        raise ValueError("SWC IDs must be unique and nonnegative")
    bad = ids[rows[:, 5] <= 0].tolist()
    if bad:
        raise ValueError(f"Nonpositive radius at SWC nodes {bad}")
    graph = nx.DiGraph()
    for row in rows:
        graph.add_node(int(row[0]), coords=row[2:6].copy(), swc_type=int(row[1]))
    for row in rows:
        node, parent = int(row[0]), int(row[6])
        if parent == -1:
            continue
        if parent == node or parent not in graph:
            raise ValueError(f"SWC node {node}: self loop or missing parent {parent}")
        graph.add_edge(parent, node)
    if allow_forest:
        validate_forest(graph)
    else:
        validate_tree(graph)
    return Source(path.resolve(), rows, graph)


def validate_forest(graph: nx.DiGraph) -> None:
    if not graph or not nx.is_directed_acyclic_graph(graph) or any(graph.in_degree(n) > 1 for n in graph):
        raise ValueError("Expected a nonempty directed acyclic SWC parent forest")
    for node, data in graph.nodes(data=True):
        coords = np.asarray(data["coords"])
        if coords.shape != (4,) or not np.isfinite(coords).all() or coords[3] <= 0:
            raise ValueError(f"Invalid model xyz/radius at node {node}: {coords}")


def validate_tree(graph: nx.DiGraph) -> int:
    roots = [n for n in graph if graph.in_degree(n) == 0]
    if len(roots) != 1 or not nx.is_arborescence(graph):
        raise ValueError(f"Expected one connected acyclic outward tree; roots={roots}")
    validate_forest(graph)
    return roots[0]


def write_swc(path: Path, graph: nx.DiGraph, source: Path, commit: str, sample_mode: str,
              *, header_lines: list[str] | None = None) -> dict:
    root = validate_tree(graph)
    if path.resolve() == source.resolve():
        raise ValueError("Refusing to overwrite original SWC")
    order = list(nx.dfs_preorder_nodes(graph, root))
    ids = {node: index + 1 for index, node in enumerate(order)}
    # Exclusive creation also protects previous outputs from accidental overwrite.
    with path.open("x", encoding="utf-8") as handle:
        if header_lines is not None:
            for line in header_lines:
                handle.write("# " + str(line).replace("\n", " ").replace("\r", " ") + "\n")
        else:
            handle.write(f"# Processed with VascularMD\n# Source: {source}\n"
                     "# Radius column is radius, not diameter; original numeric units preserved\n"
                     "# VascularMD modeling: penalized spline; radius_model=True; criterion=AIC\n"
                     f"# VascularMD commit: {commit}\n# Sampling: {sample_mode}\n"
                     "# Original file preserved\n# Generated by tools/vascularmd_smooth_swc.py\n"
                     f"# {graph.graph.get('bifurcation_swc_policy', 'Bifurcation SWC radius is a model-derived representative; see QC JSON')}\n")
        topology = graph.graph.get("topology_policy", {})
        handle.write(f"# Topology policy: {topology.get('policy', 'strict')}\n"
                     f"# Accepted merged source bifurcations: {topology.get('merged_bifurcation_swc_ids', [])}\n")
        for node in order:
            parents = list(graph.predecessors(node))
            parent = ids[parents[0]] if parents else -1
            data = graph.nodes[node]
            numbers = " ".join(format(float(x), ".17g") for x in data["coords"])
            handle.write(f"{ids[node]} {int(data['swc_type'])} {numbers} {parent}\n")
    return ids
