from pathlib import Path
import json,sys,csv,hashlib
import numpy as np
C=Path(__file__).parent;state=json.loads((C/'TASK_PATHS.json').read_text());R=Path(state['local_result'])
def read(p):return json.loads((R/p).read_text())
def sha(p):return hashlib.sha256((R/p).read_bytes()).hexdigest()
def save(p,d):(R/p).write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
full=read('PASSIVE_MICROBUBBLE_TRANSPORT_V0_VALIDATION.json');assert full['status']=='PASS';a=full['numerical'];ct=read('contracts/PASSIVE_MICROBUBBLE_TRANSPORT_V0_CONTRACT.json');dt=read('contracts/PASSIVE_TRANSPORT_TIMESTEP_CONTRACT.json');pop=read('provenance/POPULATION_IDENTITY.json');fc=read('contracts/FROZEN_FLOW_FIELD_CONTRACT.json');vis=read('VISUALIZATION_PROVENANCE.json');integrity=read('REMOTE_TO_WSL_INTEGRITY.json');label=a['selected_label'];m={c['name']:c['metrics'] for c in a['cases']};geo={c['name']:c for c in full['exact_geometry_and_every_step_RK2_replay']['cases']};c0=m['case0_'+label];c1=m['case1_'+label];c2=m['case2_'+label];c4=m['case4_mpi4_'+label];c5=m['case5_'+label];gpu=m['kokkos_'+label];g2=geo['case2_'+label];g5=geo['case5_'+label];placement=read('CASE5_PLACEMENT_LIMIT_AUDIT.json');conv=dt['details']['real']['c025_vs_c0125'];size=round(sum(p.stat().st_size for p in R.rglob('*') if p.is_file())/2**30,3)
summary={
'PASSIVE_MICROBUBBLE_TRANSPORT_V0':'PASS','DYNAMICS':'OVERDAMPED_QUASI_STEADY','EQUATION':'dX/dt = U(X)','PARTICLE_INERTIA':'OFF','NEWTON_SECOND_LAW_INTEGRATION':'OFF','BULK_DRAG':'STOKES','BUOYANCY':'OFF_IN_V0','LIFT':'OFF_IN_V0','ADDED_MASS':'OFF','BASSET_HISTORY':'OFF','BUBBLE_BUBBLE_FORCE':'OFF','WALL_HYDRODYNAMICS':'OFF','ADHESION':'OFF','RBC':'OFF','INTEGRATOR':'RK2_MIDPOINT','U_MAX_M_S':ct['field_speed_statistics']['real']['U_MAX_m_s'],'DX_M':ct['dx_m'],'C_ADV_TESTED':'0.5,0.25,0.125','SELECTED_C_ADV':dt['selected_c_adv'],'PARTICLE_DT_S':dt['particle_dt_s'],
'CASE_0_UNIFORM_PASSIVE':'PASS','CASE_0_MAX_POSITION_ERROR_M':c0['max_position_error_m'],'CASE_1_LINEAR_PASSIVE':'PASS','CASE_1_MAX_POSITION_ERROR_M':c1['max_position_error_m'],'TIMESTEP_CONVERGENCE':'PASS','DT025_VS_DT0125_FINAL_POSITION_DIFF_M':conv['final_position_difference_m'],
'CASE_2_REAL_FIELD_PASSIVE':'PASS','CASE_2_DIAMETER_UM':pop['case2']['diameters_um'][0],'CASE_2_STEPS':c2['completed_steps'],'CASE_2_PHYSICAL_TIME_S':c2['physical_time_s'],'CASE_2_TOTAL_DISPLACEMENT_UM':c2['net_displacement_m']*1e6,'CASE_2_MIN_SURFACE_WALL_GAP_UM':g2['min_internal_surface_wall_gap_m']*1e6,'CASE_2_TERMINATION_REASON':c2['termination_reason'],
'CASE_3_DIAMETER_INDEPENDENCE':'PASS','D10_UM':pop['case3']['diameters_um'][0],'D50_UM':pop['case3']['diameters_um'][1],'D90_UM':pop['case3']['diameters_um'][2],'CASE_3_MAX_POSITION_DIFFERENCE_M':a['diameter_independence']['max_position_difference_m'],
'CASE_4_MULTIPARTICLE_PASSIVE':'PASS','CASE_4_N':1000,'MPI_COMPARISON':'PASS','MPI1_MPI4_MAX_POSITION_DIFFERENCE_M':c4['mpi_position_difference_m'],'MPI1_MPI4_MAX_VELOCITY_DIFFERENCE_M_S':c4['mpi_velocity_difference_m_s'],'PARTICLES_WITH_OBSERVED_MPI_MIGRATION':c4['particles_with_observed_MPI_migration'],
'CASE_5_REAL_MULTIBUBBLE':'PASS','CASE_5_N':c5['N'],'CASE_5_TERMINATION_REASON':c5['termination_reason'],'CASE_5_PHYSICAL_TIME_S':c5['physical_time_s'],'KOKKOS_COMPATIBILITY_SMOKE':'PASS','GPU_PERFORMANCE_READY':'NO','NONFINITE_COUNT':a['nonfinite_count'],'LOST_ATOMS':a['lost_atoms'],'INVALID_QUERY_COUNT':a['invalid_query_count'],'INDEPENDENT_FINALIZER':'PASS',
'VIS_CASE0_UNIFORM_ANALYTIC':'PASS','VIS_CASE1_LINEAR_REFERENCE':'PASS','VIS_TIMESTEP_CONVERGENCE':'PASS','VIS_CASE2_REAL_TRAJECTORY':'PASS','VIS_CASE2_SPEED_TIME':'PASS','VIS_CASE2_WALL_CLEARANCE':'PASS','VIS_CASE3_DIAMETER_INDEPENDENCE':'PASS','VIS_CASE5_MULTIBUBBLE_TRAJECTORIES':'PASS','HUMAN_VISUAL_REVIEW':'PENDING','REMOTE_TO_WSL_INTEGRITY':'PASS','FORMAL_PURE_FLUID_BASELINE_MODIFIED':'NO','COUPLING_V0_BASELINE_MODIFIED':'NO','SONOVUE_SAMPLER_MODIFIED':'NO','LAMMPS_ENGINE_BASELINE_MODIFIED':'NO','FULL_MICROBUBBLE_TRANSPORT_MODEL':'PENDING','BUBBLE_BUBBLE_INTERACTION_MODEL':'PENDING','BUBBLE_BUBBLE_LUBRICATION':'PENDING','MICROBUBBLE_WALL_HYDRODYNAMICS':'PENDING','WALL_EXCLUSION':'PENDING','MICROBUBBLE_ADHESION':'PENDING','TWO_WAY_COUPLING':'OFF','FLOW_FIELD_SCIENTIFIC_STATUS':'ENGINEERING_TRANSIENT_FIELD_ONLY','TOTAL_RESULT_GIB':size,'REMOTE_RESULT_DIR':state['remote_result'],'LOCAL_RESULT_DIR':str(R),'REPORT':str(R/'PASSIVE_MICROBUBBLE_TRANSPORT_V0_REPORT.md'),'NEXT_STAGE':'USER_REVIEW_BEFORE_BUBBLE_BUBBLE_INTERACTION_V0'}
save('FINAL_SUMMARY.json',summary);(R/'FINAL_TERMINAL_SUMMARY.txt').write_text('\n'.join(f'{k} = {v}' for k,v in summary.items())+'\n')
provenance={'frozen_flow_field_sha256':fc['field_sha256'],'histogram_sha256':sha('provenance/frozen_sampler/input/FROZEN_SONOVUE_HISTOGRAM.csv'),'sampler_contract_sha256':sha('provenance/frozen_sampler/contracts/SONOVUE_SAMPLER_CONTRACT_V0.json'),'stage_contract_sha256':sha('contracts/PASSIVE_MICROBUBBLE_TRANSPORT_V0_CONTRACT.json'),'timestep_contract_sha256':sha('contracts/PASSIVE_TRANSPORT_TIMESTEP_CONTRACT.json'),'frozen_input_manifest_sha256':sha('FROZEN_INPUT_SHA256SUMS'),'geometry_sha256':sha('provenance/closed_geometry_m.stl'),'source_files':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((R/'src').glob('*')) if p.is_file()},'build':read('provenance/BUILD_PROVENANCE.json'),'Palabos_GPU_commit':fc['Palabos_GPU_commit'],'LAMMPS_commit':'9c5ab448c78a14fd534619622162ba418d6a1fb1','visualization_provenance_sha256':sha('VISUALIZATION_PROVENANCE.json'),'local_baseline_audit':read('LOCAL_BASELINE_AUDIT.json'),'remote_baseline_audit':read('provenance/BASELINE_AFTER.json'),'download':integrity,'HUMAN_VISUAL_REVIEW':'PENDING'};save('PASSIVE_TRANSPORT_PROVENANCE.json',provenance)
with (R/'PERFORMANCE_AND_CASE_SUMMARY.csv').open('w') as f:
 rows=[dict(name=n,**{k:v for k,v in d.items() if k in ['N','completed_steps','physical_time_s','termination_reason','wall_seconds','particle_steps_per_s','mpi_ranks','peak_rss_kib','nonfinite_count','invalid_query_count','lost_atoms']}) for n,d in m.items()];writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
lines=['# PASSIVE_MICROBUBBLE_TRANSPORT_V0 中文核查报告','',
'这一版微泡没有自己的惯性，它每一刻都按照所在位置的流体速度移动。',
'', '**本阶段 PASS**。这是 passive advection baseline：验证冻结流场中的直接随流输运实现。它不是完整 SonoVue 物理模型。真实流场来自 PBS/BSA 的 5000 步 smoke，保持 ENGINEERING_TRANSIENT_FIELD_ONLY；新介质入口倍率未重新校准，原场有瞬态回流，不能据此宣称真实 margination、分支概率、壁面作用或 adhesion 已验证。',
'', '## 模型与积分', '',
'正式方程为 `dX/dt=U(X)`。只有 bulk Stokes drag 且取 overdamped 平衡时，`0=3πμd(U−V)` 直接给出 `V=U`。新建独立的 `fix sonovue/passive/flow`，在内存中使用已验证的三线性插值和 midpoint RK2：`k1=U(X)`、`Xmid=X+dt*k1/2`、`k2=U(Xmid)`、`Xnew=X+dt*k2`、`Vnew=U(Xnew)`。',
'', 'RK2 对平滑速度场具有二阶精度，比 forward Euler 通常更准确；代价低于 RK4，适合作为首版大粒子数 frozen-flow 基线。其稳定性和误差仍需步长检查，本轮已做三档验证；不声称它对任意场或任意步长无条件稳定。',
'', 'LAMMPS 保留 sphere 存储、ID、ownership/migration 和邻居基础设施。推进器完全不读取质量或计算加速度，正式输入没有 nve/sphere。sphere data 文件要求的正密度采用 1 kg/m³ 作为存储占位；它没有进入输运方程，也不被解释为微泡物理密度。外部 embedding 注册 custom Fix，原 LAMMPS core、CPU/GPU 静态库与 baseline binary 均未修改。',
'', 'buoyancy、lift、added mass、Basset history、bubble-bubble force/lubrication、wall hydrodynamics/contact、adhesion、RBC、ultrasound 和 two-way feedback 全部关闭。有限尺寸只进入本轮几何安全检查。因为代数式中的 d 消去，三种直径的 bulk passive 轨迹应相同；这不意味着实际 SonoVue 运动永远与粒径无关。',
'', '## 输入冻结与时间步', '',
f'真实 HDF5 SHA256：`{fc["field_sha256"]}`，182,694 个流体节点，493×497×280；dx={ct["dx_m"]:.17g} m。读取三分量 `Velocity_m_s`，没有使用无效的 `VelocityMagnitude_m_s`。原 HDF5、STL、PBS/BSA 数值、SonoVue histogram/sampler、上一 coupling 结果逐文件校验，保持原字节身份。',
f'',f'从有效节点速度向量计算 `U_MAX={summary["U_MAX_M_S"]:.17g} m/s`。真实场采用 `dt=C_adv*dx/U_MAX`；所选 C_adv={dt["selected_c_adv"]}，dt={dt["particle_dt_s"]:.17g} s。时间步来自空间位移控制，不来自旧技术惯性 relaxation time。',
'', '第 16 节“最大合格步长”与第 17 节“.25 通过则选 .25”存在文字差异。本轮在任何数值结果产生前明确按第 17 节冻结：.5 是较粗对照，.25 通过与 .125 的收敛门则选 .25，否则选稳定且通过参考门的 .125。本轮选择 .25。',
'', '已有 synthetic uniform/linear HDF5 的网格为 8 µm。本轮所有误差门和位移控制均保守采用真实血管 dx≈0.2 µm；每个场的 dt 使用其各自实测 U_MAX。尤其 affine 场的全域最大速度较大，不能套用真实场的 U_MAX。',
'', '| 场 | U_MAX (m/s) | 所选 dt (s) |','|---|---:|---:|']
for kind,s in ct['field_speed_statistics'].items():lines.append(f'| {kind} | {s["U_MAX_m_s"]:.12g} | {dt["selected_c_adv"]*s["dt_base_s"]:.12g} |')
lines += ['', '三档数据在相同记录物理时刻比较。真实场三档均达到同一预先冻结的最大物理时长；没有对不同结束时刻强行比较末态。', '', '| 场 / 对照 | 最终位置差 (m) | 全轨迹最大差 (m) | 结果 |','|---|---:|---:|---|']
for kind,v in dt['details'].items():
 for pair,q in v.items():lines.append(f'| {kind} / {pair} | {q["final_position_difference_m"]:.10g} | {q["max_trajectory_difference_m"]:.10g} | {q["status"]} |')
lines += ['',f'最终位置差门为 0.05dx={ct["gates"]["dt_final_difference_m"]:.10g} m，全记录轨迹差门为 0.10dx={ct["gates"]["dt_max_trajectory_difference_m"]:.10g} m。.125 是离散化对照 reference，不把其自比较的零差解释为零真实误差。',
'', '## 算例结果', '', '| 算例 | 结果与证据 |','|---|---|',
f'| Case 0 uniform | 最大位置误差 {c0["max_position_error_m"]:.10g} m；最大速度误差 {c0["max_velocity_error_m_s"]:.10g} m/s；解析门 PASS。 |',
f'| Case 1 affine | DOP853 独立参考（rtol=1e-12，atol=1e-17 m），最大位置误差 {c1["max_position_error_m"]:.10g} m，最终误差 {c1["final_position_error_m"]:.10g} m；PASS。 |',
f'| Case 2 real | {c2["completed_steps"]} 步，{c2["physical_time_s"]:.12g} s，净位移 {c2["net_displacement_m"]*1e6:.12g} µm = {c2["net_displacement_m"]/ct["dx_m"]:.6g}dx；PASS。 |',
f'| Case 3 diameter independence | d10/d50/d90 的最大位置差 {a["diameter_independence"]["max_position_difference_m"]:.10g} m，最大速度差 {a["diameter_independence"]["max_velocity_difference_m_s"]:.10g} m/s；PASS。 |',
f'| Case 4 MPI1/MPI4 | 1000 个相同初态粒子，{c4["particles_with_observed_MPI_migration"]} 个粒子实际跨 rank；ID/直径 exact，最大位置差 {c4["mpi_position_difference_m"]:.10g} m、速度差 {c4["mpi_velocity_difference_m_s"]:.10g} m/s；PASS。 |',
f'| Case 5 real population | 冻结 N={c5["N"]}，{c5["completed_steps"]} 个已接受步，{c5["physical_time_s"]:.12g} s；在下一步预测泡间重叠时 SAFETY_STOP，安全停止行为 PASS。 |',
f'| GPU/Kokkos | 1000 粒子、{gpu["completed_steps"]} 步，有限性/ID/解析轨迹检查 PASS；GPU_PERFORMANCE_READY 仍为 NO。 |',
'',f'Case 0/1/2 seeds 为 20260922/20260923/20260924；Case 2 在几何搜索前选定 d50-like sample，直径 {summary["CASE_2_DIAMETER_UM"]:.15g} µm。Case 3（seed=20260925）的实际采样直径为 {pop["case3"]["diameters_um"]} µm；Case 4 seed=20260926，Case 5 seed=20260927。完整原样本、source IDs、seed 与 histogram SHA 保存在 populations/ 和 provenance/。',
'', '## 真实路径与安全停止', '',
f'Case 2 起点满足 center-wall>radius+5dx。最大时间在正式运行前按 domain diagonal/U_MAX 冻结为 {c2["physical_time_s"]:.12g} s，终止原因为 {c2["termination_reason"]}。这条路径明显超过上一 coupling 的微秒级 smoke，且净位移超过 10dx。',
f'',f'独立 Python 从初态重建全部内部 RK2 步，并对原闭合 STL 计算三角面距离、enclosure、每个中点和完整步间线段的距离下界。Case 2 全部内部步的最小球表面壁间隙为 {g2["min_internal_surface_wall_gap_m"]*1e6:.12g} µm，大于 3dx={3*ct["dx_m"]*1e6:.12g} µm。相同 dt 的独立重建位置最大差 {g2["max_independent_position_difference_m"]:.10g} m。',
f'',f'Case 5 在冻结的 {placement["candidate_count"]:,} 个 all-fluid cell-center 候选目录中，原样本 3 和 5 无满足初始 5dx 壁间隙的候选；其余 8 个均已互不重叠地放置，因此 8 是该固定候选目录中的最大可放置计数。它不是对连续空间最优 packing 的宣称。没有重抽、缩小或人工替换粒径。',
f'',f'Case 5 在所有已接受的中点与扫掠步间路径上保持无重叠，最小泡间表面间隙 {g5["min_accepted_pair_gap_m"]*1e6:.10g} µm。独立检查重现下一步的重叠预测：{g5["next_step_rejection_evidence"]}。下一步未被接受；没有用 granular contact 或其它未授权物理作用处理接触。',
'', '安全停止通过 LAMMPS 已有 timer halt 机制在下一步开始前结束 run；最后记录仍属于有效的已接受状态。invalid midpoint/end query 会硬停止并保留 invalid 计数；本轮正式轨迹 invalid=0。安全监控是模型适用范围的停止条件，不是 wall force 或 bubble-bubble force。',
'', '## 独立核查、可视化与性能', '',
f'全部 16 次实际运行各执行一次，NONFINITE_COUNT={a["nonfinite_count"]}、LOST_ATOMS={a["lost_atoms"]}、INVALID_QUERY_COUNT={a["invalid_query_count"]}。独立 Python 数值 finalizer 在远端与 WSL 都通过；WSL 另完成逐内部步 RK2/几何/泡间扫掠复核。新增 C++ STL 距离模块对 2000 个独立 VTK 距离样本通过 1e-12 m 门，最大误差 {read("validation/WALL_DISTANCE_AUDIT.json")["maximum_error_m"]:.10g} m。',
'', '不逐步写磁盘；生产真实单泡保存约 754 个轨迹点，linear 约 1001 个。较短 uniform/MPI 例各约 201 点，GPU smoke 101 点，提前停止的 8 泡例各 26 点。初始、最终和 safety-stop 均保存；没有为输出时刻改变积分步长。',
f'',f'性能只记录，不设门。GPU 100 ms 采样观测 utilization 峰值 {gpu["gpu_utilization_peak_percent"]:g}%、VRAM 峰值 {gpu["gpu_vram_peak_mib"]:g} MiB。CPU/GPU wall time、MPI ranks、采样到的进程树 RAM 峰值和 particle steps/s 见 PERFORMANCE_AND_CASE_SUMMARY.csv；速率包含进程启动、场加载和记录开销，不作专门性能结论。未做 CUDA/Kokkos 优化。',
'', '首次默认 appended/base64 VTP 被当前 VTK 读取器拒绝，回读门及时捕获。保留失败文件后，输出改为 17 位有效数字的 ASCII VTP，并通过 XML 解析及 VTK 坐标/数组回读；数值轨迹没有变化，求解器没有重跑。',
'', '以下图全部由 scripts/visualize_passive.py 从冻结 CSV/HDF5/STL 独立生成，未平滑或手改轨迹。VISUALIZATION_PROVENANCE.json 记录逐图源文件 SHA256、脚本 SHA256 和输出 SHA256。所有 VTP 的点坐标和 point-data 数组均回读比较与原 CSV 完全一致。',
'', '**HUMAN_VISUAL_REVIEW = PENDING**。自动生成、文件/数据一致性检查和机器查看均不能替代人工审阅。',
'']
for filename,desc in [('VIS_CASE0_UNIFORM_ANALYTIC.png','Uniform 解析对照与误差'),('VIS_CASE1_LINEAR_REFERENCE.png','Affine 独立 DOP853 对照'),('VIS_TIMESTEP_CONVERGENCE.png','三档步长收敛与所选 production 档位'),('VIS_CASE2_REAL_TRAJECTORY.png','真实血管中的 XY/XZ/YZ 正交投影'),('VIS_CASE2_SPEED_TIME.png','粒子速度与所在位置流速'),('VIS_CASE2_WALL_CLEARANCE.png','真实轨迹壁间隙'),('VIS_CASE3_DIAMETER_INDEPENDENCE.png','当前 minimal V0 的粒径无关性'),('VIS_CASE5_MULTIBUBBLE_TRAJECTORIES.png','8 泡路径及 safety-stop')]:lines += [f'![{desc}](visualization/{filename})','']
lines += ['ParaView：共同打开 visualization/FROZEN_LUMEN.vtp 和 CASE2_TRAJECTORY.vtp / CASE5_TRAJECTORIES.vtp。几何及 VTP 点坐标单位为 m；point data 包含 time_s、diameter_um、speed_m_s、fluid_speed_m_s、center_wall_distance_um、surface_wall_gap_um。原始 STL 身份见 FROZEN_LUMEN_REFERENCE.json。',
'',f'结果约 {size:.3f} GiB。远端数值封存 {integrity["remote_seal"]["files"]} 个 SHA256 校验项已下载并逐项通过。网络变慢后仅切换为压缩文件续传，求解器没有重跑。NUMERICAL_EVIDENCE_SHA256SUMS 保留数值封存，最终 SHA256SUMS 覆盖新增本地审计和图件。',
'', '公开复核入口：', '', '```bash','sha256sum -c SHA256SUMS','/usr/bin/python3 -B finalize_passive_transport_v0.py --root "$PWD"','```','', '最终器完全独立于 C++ 执行程序，读取原 CSV/dumps/HDF5/contracts；会重新写审计 JSON 和图件。需要保留封存目录字节不变时，在其副本执行。依赖 NumPy、SciPy、h5py、VTK、Matplotlib。',
'',f'远端结果：`{state["remote_result"]}`。',f'本地结果：`{R}`。',
'', '允许结论：OVERDAMPED_TRANSPORT_IMPLEMENTATION、PASSIVE_ADVECTION、FROZEN_FLOW_MICROBUBBLE_TRANSPORT 的实现核查 PASS。FULL_MICROBUBBLE_TRANSPORT_MODEL、bubble-bubble/lubrication、wall hydrodynamics/exclusion、adhesion 保持 PENDING；RBC/two-way coupling OFF。',
'', '本阶段结束并停止。NEXT_STAGE=USER_REVIEW_BEFORE_BUBBLE_BUBBLE_INTERACTION_V0。']
(R/'PASSIVE_MICROBUBBLE_TRANSPORT_V0_REPORT.md').write_text('\n'.join(lines)+'\n')
(R/'README.md').write_text('先读 PASSIVE_MICROBUBBLE_TRANSPORT_V0_REPORT.md 与 FINAL_TERMINAL_SUMMARY.txt。\n\n公开独立复核：`/usr/bin/python3 -B finalize_passive_transport_v0.py --root "$PWD"`。它会重新生成审计与图件；保留封存包时请在副本运行。\n\nCMakeLists.txt 使用只读的上一阶段 LAMMPS build_cpu/build_gpu 静态库，以 ENGINE_ROOT 参数指定原构建目录。当前 CUDA 路径对应本 Vast 的 13.2 环境，迁往其他平台需重新配置。binaries/ 是本次实际构建证据，保留原 build-tree runtime 路径，并非通用可搬移二进制。\n\n正式 frozen contract 位于 contracts/PASSIVE_MICROBUBBLE_TRANSPORT_V0_CONTRACT.json；派生所选步长位于 PASSIVE_TRANSPORT_TIMESTEP_CONTRACT.json。case0/1/2 选中档位的已完成轨迹直接用作 production V0 证据，没有额外重复求解。其它未选中的生产输入保留但未执行。\n\n本任务程序使用 HWLOC_COMPONENTS=-gl、OMP_NUM_THREADS=1。-gl 仅跳过 GL 显示拓扑探测。scripts/run_validation.py 是已完成的一次性执行记录，会拒绝重复运行已有算例。\n\nParaView 同时打开 visualization/FROZEN_LUMEN.vtp 和 CASE2_TRAJECTORY.vtp / CASE5_TRAJECTORIES.vtp。坐标单位 m。HUMAN_VISUAL_REVIEW=PENDING。\n')
print(json.dumps({'status':'PASS','summary':summary},ensure_ascii=False,indent=2))
