name: ulm-dolfinx
channels:
  - conda-forge
dependencies:
  - python=3.12
  - fenics-dolfinx>=0.9,<0.11
  - python-gmsh>=4.13,<5
  - cairo>=1.18
  - mpi4py
  - pyamg
  - numpy
  - scipy
  - matplotlib
  - shapely>=2
  - pyyaml
  - tqdm
  - pip
  - pip:
