from pathlib import Path
import json,hashlib,numpy as np
R=Path(__file__).resolve().parents[1];source=json.loads((R/'OPEN_SOURCE_TOOL_PROVENANCE.json').read_text());ref=json.loads((R/'input/WALL_REFERENCE_CONVENTION.json').read_text())
C={'contract_name':'FIXED_MULTIBLOB_WALL_FEASIBILITY_AUDIT_V0','status':'FROZEN_BEFORE_PHYSICAL_COMPARISONS','primary':'Pecnut/stokesian-dynamics','primary_commit':source[0]['commit'],'model':'FIXED_HARD_SPHERES; full native far-field force/torque/stresslet plus native pair lubrication excess','secondary':'NONE_RUNTIME; RMBW and RigidBodyIB audited for capability only','native_coefficients':'required radius ratios generated with original upstream near/midfield scripts; no interpolation between lambda values','mu_Pa_s':.001,'diameters_m':{k:2*v for k,v in ref['radii_m'].items()},'radii_m':ref['radii_m'],'table_sha256':hashlib.sha256((R/'input/RMBW_WALL_RESISTANCE_TABLE_V0.h5').read_bytes()).hexdigest(),'STL_sha256':hashlib.sha256((R/'input/closed_geometry_m.stl').read_bytes()).hexdigest(),
 'epsilon':[.001,.002,.005,.01,.02,.05,.1,.2,.5,1.,2.,5.],'core':[.01,.2],'ultra_near':[.001,.01],'betas':[.5,.25,.125,.0625],'optional_beta':.03125,'layouts':['HEX','SQUARE'],'layers':[1,2,3],'spacing_ratio_primary':1.01,'spacing_ratio_sweep':[1.01,1.05,1.1],'nominal_plane':'z=0; first-layer sphere centers z=-a_w','global_effective_offset':None,'offset_fitting':'NOT_USED',
 'phase':'bead center; bridge midpoint; pore (hex triangle barycenter / square cell center); 4x4 offset uniform grid (i+.5,j+.5)/4; 19 positions total','patch_radius_over_a':[4,6,8,12],'patch_shape':'circular; deterministic finite lattice; center fixed independent of target phase','layers_rule':'AB stagger; HEX dz=s*sqrt(2/3), shift=(b1+b2)/3; SQUARE dz=s/sqrt(2), shift=(b1+b2)/2','hard_sphere_overlap':'NO; check all wall pairs and target/wall; upstream minimum s_dash=2.00001 regularizes touching diagnostic only',
 'seeds':{'actions':2026091611,'dissipation':2026091612,'repeated_queries':2026091613},'action_vectors':256,'dissipation_vectors':10000,'work_conjugate_scaling':'Rhat=diag(1/sqrt(6*pi*mu*a),...,1/sqrt(8*pi*mu*a^3)) R diag(same); q order Vxyz,Oxyz; compare total and excess separately',
 'gates':{'free_translation':1e-4,'free_rotation':1e-4,'free_TR_absolute':1e-8,'core_TT_normal':.05,'core_TT_parallel':.05,'core_action':.05,'core_RR':.1,'core_TR':.1,'phase_TT':.05,'phase_RR':.1,'phase_TR':.1,'hex_tangent_anisotropy':.05,'hex_RR_anisotropy':.1,'patch_TT':.02,'patch_RR':.05,'patch_TR':.05,'reciprocity':1e-8,'eigenvalue_min_strictly_greater_than':0.,'native_adapter_identity':1e-10,'linear_residual':1e-10,'leakage_proxy_normalized':.05,'leakage_layer3_over_layer1':.8,'cylinder_self_convergence_action':.05},
 'leakage_metric':'lower force/torque-free probe Vz induced by upper Fz / corresponding no-wall two-probe Vz; all fixed wall U/O/E=0; upper at z=2a, lower at bottom wall envelope minus2a; probe radius=a; zero background','phase_spread':'(max-min)/abs(mean); TR signed isotropic projection; denominator floor1e-12 for exact zeros; report means std min max CV','anisotropy':'directional 0,45,90 deg; (max-min)/abs(mean); rotation axis parallel plane; TR projected tangent force versus normal-cross-tangent rotation',
 'coarse_to_fine':'start beta0.5; beta0.25 next if free-space/native gates pass. Stop finer physics if beta0.25 worst core action error>0.5 AND worst phase TT spread>0.1 AND core mean-action improvement vs beta0.5 <0.05 absolute, or nonpositive matrices. Otherwise continue listed betas where memory/time preflight passes. Do not use a smaller patch to pretend fixed-extent refinement.',
 'curved_gate':'ONLY_IF_PLANAR_CORE_PASS; otherwise NOT_RUN_PLANAR_GATE_FAILED','cylinder_R_over_a':[2,3,5,10,20],'real_gate':'ONLY_IF_PLANAR_AND_CYLINDER_SELF_CONVERGED','real_pilot_count':12,'real_site_rule':'deterministic representatives ranked by prior RMS/normal spread and spatial coverage; no per-patch tuning','performance_wall_counts':[100,500,1000,2000],'performance_optional_counts':[5000,10000],'repeated_query_count':100,'CPU_BLAS_threads':4,'GPU_optimization':False,'per_query_timeout_s':180,'estimated_peak_dense_memory_cap_GiB':20,'memory_reserve_fraction':.4,'runtime_total_hard_limit_s':3600,'budget_role':'engineering stop bounds, not scientific gates; retain incomplete status without pretending measured',
 'wall_cache':'exact wall-wall M_inf block factorization; target Schur complement; native R2B wall-wall terms multiply prescribed zero motions and do not enter target rows. Verify identity against full native assembly including wall-wall lubrication before using this reuse.',
 'frozen_baselines_modified':False,'production_migration':False,'adhesion':False,'buoyancy':False,'lift':False,'RBC':False,'two_way_Palabos':False,'next_stage':'RECOMMENDED_ONLY','human_visual_review':'PENDING'}
assert C['table_sha256']=='71e62ef6bc22edc66ae0c4d1dcc224378c2f6c5d3848578f3fbedd2cd9a43f98';assert C['STL_sha256']=='840da5e1c43ec31ac70ec781cbf75b32940bc73538b5dba83c58af1ddf5e36fb'
p=R/'contracts/FIXED_MULTIBLOB_WALL_FEASIBILITY_CONTRACT.json';assert not p.exists();p.write_text(json.dumps(C,indent=2)+'\n');print('CONTRACT_FROZEN',hashlib.sha256(p.read_bytes()).hexdigest())
