#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif

#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      if !defined(Py_GIL_DISABLED)
#        define Py_LIMITED_API
#      else
#        define Py_LIMITED_API 0x030f0000
#      endif
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>
#include <stdlib.h>
#include <string.h>


/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyLong_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyLong_FromLong((long)x) :                                   \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyLong_FromLong((long)x) :                                   \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFCx specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.11.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'language': 'C',
//   'part': 'full',
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron

void tabulate_tensor_integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    void* custom_data)
{
// Quadrature rules
static const double weights_818[24] = {0.006653791709694649, 0.006653791709694649, 0.006653791709694649, 0.006653791709694649, 0.001679535175886783, 0.001679535175886783, 0.001679535175886783, 0.001679535175886783, 0.009226196923942399, 0.009226196923942399, 0.009226196923942399, 0.009226196923942399, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283, 0.008035714285714283};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_D100_Q818[1][1][24][10] = {{{{0.1415885149633931, 0.4247655448901796, 0.0, 0.0, 0.0, 0.8584114850366068, 0.8584114850366066, -0.8584114850366065, -0.8584114850366069, -0.5663540598535728},
  {-0.42476554489018, -0.1415885149633934, 0.0, 0.0, 0.0, 0.858411485036607, 0.8584114850366068, -0.8584114850366062, -0.8584114850366067, 0.5663540598535733},
  {0.1415885149633931, -0.1415885149633934, 0.0, 0.0, 0.0, 1.42476554489018, 0.8584114850366066, -1.424765544890179, -0.8584114850366068, 0.0},
  {0.1415885149633932, -0.1415885149633934, 0.0, 0.0, 0.0, 0.8584114850366069, 1.42476554489018, -0.8584114850366061, -1.42476554489018, 0.0},
  {0.8373041658615549, 2.511912497584664, 0.0, 0.0, 0.0, 0.1626958341384443, 0.1626958341384445, -0.1626958341384462, -0.162695834138446, -3.349216663446219},
  {-2.511912497584664, -0.8373041658615551, 0.0, 0.0, 0.0, 0.1626958341384463, 0.1626958341384459, -0.1626958341384445, -0.1626958341384447, 3.349216663446219},
  {0.8373041658615543, -0.8373041658615551, 0.0, 0.0, 0.0, 3.511912497584666, 0.1626958341384453, -3.511912497584663, -0.1626958341384455, 0.0},
  {0.8373041658615549, -0.8373041658615548, 0.0, 0.0, 0.0, 0.1626958341384453, 3.511912497584664, -0.1626958341384446, -3.511912497584664, 0.0},
  {-0.2893515605691021, -0.8680546817073078, 0.0, 0.0, 0.0, 1.289351560569104, 1.289351560569103, -1.289351560569102, -1.289351560569103, 1.15740624227641},
  {0.8680546817073085, 0.2893515605691028, 0.0, 0.0, 0.0, 1.289351560569103, 1.289351560569102, -1.289351560569102, -1.289351560569103, -1.157406242276411},
  {-0.2893515605691019, 0.2893515605691029, 0.0, 0.0, 0.0, 0.1319453182926923, 1.289351560569103, -0.1319453182926921, -1.289351560569103, 0.0},
  {-0.2893515605691021, 0.2893515605691027, 0.0, 0.0, 0.0, 1.289351560569103, 0.1319453182926924, -1.289351560569102, -0.1319453182926925, 0.0},
  {-1.412022659166597, 0.07868932583326342, 0.0, 0.0, 0.0, 0.2546440075000704, 0.2546440075000702, -0.2546440075000697, -0.2546440075000698, 1.333333333333333},
  {-1.412022659166597, -0.7453559924999301, 0.0, 0.0, 0.0, 0.2546440075000706, 1.078689325833264, -0.2546440075000693, -1.078689325833263, 2.157378651666527},
  {-1.412022659166597, -0.7453559924999302, 0.0, 0.0, 0.0, 1.078689325833265, 0.2546440075000704, -1.078689325833263, -0.2546440075000697, 2.157378651666527},
  {-0.07868932583326367, 1.412022659166596, 0.0, 0.0, 0.0, 0.2546440075000696, 0.2546440075000697, -0.2546440075000703, -0.2546440075000703, -1.333333333333333},
  {-0.0786893258332635, -0.7453559924999301, 0.0, 0.0, 0.0, 0.2546440075000702, 2.412022659166596, -0.2546440075000693, -2.412022659166596, 0.8240453183331939},
  {-0.07868932583326389, -0.7453559924999303, 0.0, 0.0, 0.0, 2.412022659166598, 0.2546440075000702, -2.412022659166595, -0.25464400750007, 0.8240453183331935},
  {0.7453559924999297, -0.7453559924999302, 0.0, 0.0, 0.0, 2.412022659166597, 1.078689325833263, -2.412022659166595, -1.078689325833264, 0.0},
  {0.7453559924999301, 0.0786893258332635, 0.0, 0.0, 0.0, 0.2546440075000698, 2.412022659166596, -0.2546440075000697, -2.412022659166596, -0.8240453183331934},
  {0.7453559924999299, 1.412022659166596, 0.0, 0.0, 0.0, 1.078689325833263, 0.2546440075000695, -1.078689325833264, -0.2546440075000706, -2.157378651666527},
  {0.7453559924999299, -0.7453559924999301, 0.0, 0.0, 0.0, 1.078689325833264, 2.412022659166596, -1.078689325833263, -2.412022659166596, 0.0},
  {0.7453559924999298, 0.07868932583326334, 0.0, 0.0, 0.0, 2.412022659166597, 0.2546440075000698, -2.412022659166595, -0.2546440075000703, -0.8240453183331937},
  {0.74535599249993, 1.412022659166596, 0.0, 0.0, 0.0, 0.2546440075000694, 1.078689325833263, -0.2546440075000704, -1.078689325833264, -2.157378651666526}}}};
static const double FE1_C1_D010_Q818[1][1][24][10] = {{{{0.1415885149633931, 0.0, -0.1415885149633934, 0.0, 0.8584114850366064, 0.0, 1.424765544890179, -0.8584114850366067, 0.0, -1.42476554489018},
  {-0.42476554489018, 0.0, -0.1415885149633934, 0.0, 0.8584114850366066, 0.0, 0.8584114850366065, -0.8584114850366066, 0.5663540598535732, -0.8584114850366069},
  {0.1415885149633932, 0.0, -0.1415885149633934, 0.0, 1.42476554489018, 0.0, 0.8584114850366067, -1.424765544890179, 0.0, -0.8584114850366069},
  {0.1415885149633933, 0.0, 0.4247655448901796, 0.0, 0.8584114850366066, 0.0, 0.8584114850366066, -0.8584114850366066, -0.5663540598535729, -0.8584114850366069},
  {0.8373041658615549, 0.0, -0.8373041658615548, 0.0, 0.162695834138444, 0.0, 3.511912497584663, -0.1626958341384458, 0.0, -3.511912497584664},
  {-2.511912497584664, 0.0, -0.8373041658615547, 0.0, 0.1626958341384453, 0.0, 0.162695834138445, -0.1626958341384457, 3.349216663446219, -0.1626958341384454},
  {0.8373041658615545, 0.0, -0.8373041658615548, 0.0, 3.511912497584665, 0.0, 0.1626958341384455, -3.511912497584663, 0.0, -0.1626958341384456},
  {0.8373041658615549, 0.0, 2.511912497584664, 0.0, 0.1626958341384455, 0.0, 0.1626958341384452, -0.162695834138445, -3.349216663446218, -0.1626958341384453},
  {-0.2893515605691021, 0.0, 0.2893515605691028, 0.0, 1.289351560569103, 0.0, 0.1319453182926924, -1.289351560569103, 0.0, -0.1319453182926925},
  {0.8680546817073086, 0.0, 0.2893515605691028, 0.0, 1.289351560569103, 0.0, 1.289351560569103, -1.289351560569103, -1.157406242276412, -1.289351560569103},
  {-0.2893515605691019, 0.0, 0.2893515605691028, 0.0, 0.1319453182926918, 0.0, 1.289351560569103, -0.1319453182926925, 0.0, -1.289351560569103},
  {-0.2893515605691021, 0.0, -0.8680546817073078, 0.0, 1.289351560569103, 0.0, 1.289351560569103, -1.289351560569103, 1.15740624227641, -1.289351560569103},
  {-1.412022659166597, 0.0, -0.7453559924999299, 0.0, 0.2546440075000696, 0.0, 1.078689325833263, -0.2546440075000704, 2.157378651666527, -1.078689325833264},
  {-1.412022659166597, 0.0, 0.07868932583326359, 0.0, 0.2546440075000699, 0.0, 0.2546440075000698, -0.2546440075000702, 1.333333333333333, -0.25464400750007},
  {-1.412022659166597, 0.0, -0.7453559924999301, 0.0, 1.078689325833264, 0.0, 0.25464400750007, -1.078689325833263, 2.157378651666527, -0.2546440075000701},
  {-0.07868932583326353, 0.0, -0.74535599249993, 0.0, 0.254644007500069, 0.0, 2.412022659166596, -0.2546440075000704, 0.8240453183331934, -2.412022659166597},
  {-0.07868932583326346, 0.0, 1.412022659166596, 0.0, 0.25464400750007, 0.0, 0.2546440075000698, -0.2546440075000699, -1.333333333333333, -0.25464400750007},
  {-0.07868932583326378, 0.0, -0.7453559924999299, 0.0, 2.412022659166597, 0.0, 0.25464400750007, -2.412022659166596, 0.8240453183331936, -0.2546440075000702},
  {0.7453559924999298, 0.0, 0.0786893258332635, 0.0, 2.412022659166597, 0.0, 0.25464400750007, -2.412022659166596, -0.8240453183331934, -0.2546440075000701},
  {0.7453559924999301, 0.0, 1.412022659166596, 0.0, 0.2546440075000697, 0.0, 1.078689325833263, -0.2546440075000699, -2.157378651666526, -1.078689325833263},
  {0.7453559924999299, 0.0, -0.7453559924999302, 0.0, 1.078689325833263, 0.0, 2.412022659166596, -1.078689325833264, 0.0, -2.412022659166596},
  {0.74535599249993, 0.0, 1.412022659166596, 0.0, 1.078689325833264, 0.0, 0.2546440075000699, -1.078689325833263, -2.157378651666526, -0.2546440075000699},
  {0.7453559924999299, 0.0, -0.7453559924999299, 0.0, 2.412022659166596, 0.0, 1.078689325833263, -2.412022659166596, 0.0, -1.078689325833264},
  {0.7453559924999299, 0.0, 0.0786893258332635, 0.0, 0.2546440075000691, 0.0, 2.412022659166595, -0.2546440075000703, -0.8240453183331937, -2.412022659166596}}}};
static const double FE1_C2_D001_Q818[1][1][24][10] = {{{{0.1415885149633932, 0.0, 0.0, -0.1415885149633932, 0.8584114850366065, 1.42476554489018, 0.0, 0.0, -0.858411485036607, -1.42476554489018},
  {-0.4247655448901799, 0.0, 0.0, -0.1415885149633933, 0.8584114850366064, 0.8584114850366067, 0.0, 0.5663540598535732, -0.8584114850366068, -0.8584114850366069},
  {0.1415885149633933, 0.0, 0.0, 0.4247655448901799, 0.8584114850366067, 0.858411485036607, 0.0, -0.5663540598535727, -0.8584114850366068, -0.858411485036607},
  {0.1415885149633933, 0.0, 0.0, -0.1415885149633932, 1.424765544890179, 0.8584114850366069, 0.0, 0.0, -1.42476554489018, -0.858411485036607},
  {0.8373041658615547, 0.0, 0.0, -0.8373041658615548, 0.162695834138445, 3.511912497584664, 0.0, 0.0, -0.1626958341384461, -3.511912497584665},
  {-2.511912497584664, 0.0, 0.0, -0.8373041658615552, 0.1626958341384446, 0.1626958341384445, 0.0, 3.349216663446219, -0.1626958341384455, -0.1626958341384452},
  {0.8373041658615547, 0.0, 0.0, 2.511912497584664, 0.1626958341384459, 0.1626958341384463, 0.0, -3.349216663446218, -0.1626958341384454, -0.1626958341384456},
  {0.8373041658615549, 0.0, 0.0, -0.837304165861555, 3.511912497584664, 0.162695834138446, 0.0, 0.0, -3.511912497584664, -0.1626958341384453},
  {-0.2893515605691019, 0.0, 0.0, 0.2893515605691029, 1.289351560569103, 0.1319453182926926, 0.0, 0.0, -1.289351560569103, -0.1319453182926925},
  {0.8680546817073085, 0.0, 0.0, 0.2893515605691031, 1.289351560569103, 1.289351560569103, 0.0, -1.157406242276411, -1.289351560569103, -1.289351560569103},
  {-0.2893515605691018, 0.0, 0.0, -0.8680546817073077, 1.289351560569102, 1.289351560569102, 0.0, 1.15740624227641, -1.289351560569103, -1.289351560569103},
  {-0.2893515605691019, 0.0, 0.0, 0.289351560569103, 0.131945318292692, 1.289351560569103, 0.0, 0.0, -0.1319453182926927, -1.289351560569103},
  {-1.412022659166597, 0.0, 0.0, -0.7453559924999301, 0.2546440075000692, 1.078689325833263, 0.0, 2.157378651666526, -0.2546440075000704, -1.078689325833264},
  {-1.412022659166597, 0.0, 0.0, -0.7453559924999302, 1.078689325833263, 0.2546440075000693, 0.0, 2.157378651666526, -1.078689325833264, -0.2546440075000699},
  {-1.412022659166597, 0.0, 0.0, 0.07868932583326343, 0.2546440075000695, 0.2546440075000698, 0.0, 1.333333333333333, -0.2546440075000702, -0.25464400750007},
  {-0.07868932583326353, 0.0, 0.0, -0.7453559924999299, 0.2546440075000693, 2.412022659166596, 0.0, 0.8240453183331935, -0.2546440075000706, -2.412022659166597},
  {-0.07868932583326345, 0.0, 0.0, -0.7453559924999301, 2.412022659166596, 0.2546440075000703, 0.0, 0.8240453183331937, -2.412022659166596, -0.25464400750007},
  {-0.07868932583326353, 0.0, 0.0, 1.412022659166597, 0.2546440075000702, 0.2546440075000704, 0.0, -1.333333333333333, -0.25464400750007, -0.2546440075000703},
  {0.7453559924999299, 0.0, 0.0, 1.412022659166597, 1.078689325833264, 0.2546440075000707, 0.0, -2.157378651666526, -1.078689325833263, -0.2546440075000702},
  {0.74535599249993, 0.0, 0.0, -0.74535599249993, 2.412022659166596, 1.078689325833264, 0.0, 0.0, -2.412022659166596, -1.078689325833264},
  {0.7453559924999297, 0.0, 0.0, 0.07868932583326375, 0.2546440075000698, 2.412022659166596, 0.0, -0.8240453183331933, -0.2546440075000706, -2.412022659166597},
  {0.7453559924999299, 0.0, 0.0, 0.07868932583326359, 2.412022659166596, 0.2546440075000708, 0.0, -0.8240453183331928, -2.412022659166596, -0.2546440075000701},
  {0.74535599249993, 0.0, 0.0, 1.412022659166597, 0.2546440075000704, 1.078689325833264, 0.0, -2.157378651666526, -0.2546440075000703, -1.078689325833264},
  {0.7453559924999298, 0.0, 0.0, -0.7453559924999299, 1.078689325833263, 2.412022659166596, 0.0, 0.0, -1.078689325833264, -2.412022659166596}}}};
for (int iq = 0; iq < 24; ++iq)
{
  // ------------------------ 
  // Section: Jacobian
  // Inputs: FE1_C2_D001_Q818, coordinate_dofs, FE1_C0_D100_Q818, FE1_C1_D010_Q818
  // Outputs: J0_c3, J0_c2, J0_c1, J0_c8, J0_c0, J0_c5, J0_c7, J0_c4, J0_c6
  double J0_c4 = 0.0;
  double J0_c8 = 0.0;
  double J0_c5 = 0.0;
  double J0_c7 = 0.0;
  double J0_c0 = 0.0;
  double J0_c3 = 0.0;
  double J0_c6 = 0.0;
  double J0_c1 = 0.0;
  double J0_c2 = 0.0;
  {
    for (int ic = 0; ic < 10; ++ic)
    {
      J0_c4 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D010_Q818[0][0][iq][ic];
      J0_c8 += coordinate_dofs[(ic) * 3 + 2] * FE1_C2_D001_Q818[0][0][iq][ic];
      J0_c5 += coordinate_dofs[(ic) * 3 + 1] * FE1_C2_D001_Q818[0][0][iq][ic];
      J0_c7 += coordinate_dofs[(ic) * 3 + 2] * FE1_C1_D010_Q818[0][0][iq][ic];
      J0_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D100_Q818[0][0][iq][ic];
      J0_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D100_Q818[0][0][iq][ic];
      J0_c6 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D100_Q818[0][0][iq][ic];
      J0_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D010_Q818[0][0][iq][ic];
      J0_c2 += coordinate_dofs[(ic) * 3] * FE1_C2_D001_Q818[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Intermediates
  // Inputs: J0_c3, J0_c2, J0_c1, J0_c8, J0_c0, J0_c5, J0_c7, J0_c4, J0_c6
  // Outputs: fw0, fw1, fw2, fw3, fw4, fw5, fw6, fw7, fw8, fw9, fw10, fw11, fw12, fw13, fw14, fw15, fw16, fw17, fw18, fw19, fw20, fw21, fw22, fw23, fw24, fw25, fw26, fw27, fw28, fw29, fw30, fw31, fw32, fw33, fw34, fw35, fw36, fw37, fw38, fw39, fw40, fw41, fw42, fw43, fw44
  double fw0 = 0;
  double fw1 = 0;
  double fw2 = 0;
  double fw3 = 0;
  double fw4 = 0;
  double fw5 = 0;
  double fw6 = 0;
  double fw7 = 0;
  double fw8 = 0;
  double fw9 = 0;
  double fw10 = 0;
  double fw11 = 0;
  double fw12 = 0;
  double fw13 = 0;
  double fw14 = 0;
  double fw15 = 0;
  double fw16 = 0;
  double fw17 = 0;
  double fw18 = 0;
  double fw19 = 0;
  double fw20 = 0;
  double fw21 = 0;
  double fw22 = 0;
  double fw23 = 0;
  double fw24 = 0;
  double fw25 = 0;
  double fw26 = 0;
  double fw27 = 0;
  double fw28 = 0;
  double fw29 = 0;
  double fw30 = 0;
  double fw31 = 0;
  double fw32 = 0;
  double fw33 = 0;
  double fw34 = 0;
  double fw35 = 0;
  double fw36 = 0;
  double fw37 = 0;
  double fw38 = 0;
  double fw39 = 0;
  double fw40 = 0;
  double fw41 = 0;
  double fw42 = 0;
  double fw43 = 0;
  double fw44 = 0;
  {
    double sv_818_0 = J0_c4 * J0_c8;
    double sv_818_1 = J0_c5 * J0_c7;
    double sv_818_2 = -sv_818_1;
    double sv_818_3 = sv_818_0 + sv_818_2;
    double sv_818_4 = J0_c0 * sv_818_3;
    double sv_818_5 = J0_c3 * J0_c8;
    double sv_818_6 = J0_c5 * J0_c6;
    double sv_818_7 = -sv_818_6;
    double sv_818_8 = sv_818_5 + sv_818_7;
    double sv_818_9 = -J0_c1;
    double sv_818_10 = sv_818_8 * sv_818_9;
    double sv_818_11 = sv_818_4 + sv_818_10;
    double sv_818_12 = J0_c3 * J0_c7;
    double sv_818_13 = J0_c4 * J0_c6;
    double sv_818_14 = -sv_818_13;
    double sv_818_15 = sv_818_12 + sv_818_14;
    double sv_818_16 = J0_c2 * sv_818_15;
    double sv_818_17 = sv_818_11 + sv_818_16;
    double sv_818_18 = sv_818_3 / sv_818_17;
    double sv_818_19 = -J0_c8;
    double sv_818_20 = J0_c3 * sv_818_19;
    double sv_818_21 = sv_818_6 + sv_818_20;
    double sv_818_22 = sv_818_21 / sv_818_17;
    double sv_818_23 = sv_818_15 / sv_818_17;
    double sv_818_24 = 0.0001273239544735163 * sv_818_18;
    double sv_818_25 = 0.0001273239544735163 * sv_818_22;
    double sv_818_26 = 0.0001273239544735163 * sv_818_23;
    double sv_818_27 = sv_818_24 + sv_818_24;
    double sv_818_28 = sv_818_25 + sv_818_25;
    double sv_818_29 = sv_818_26 + sv_818_26;
    double sv_818_30 = sv_818_27 / 2;
    double sv_818_31 = sv_818_28 / 2;
    double sv_818_32 = sv_818_29 / 2;
    double sv_818_33 = sv_818_30 * sv_818_30;
    double sv_818_34 = sv_818_30 * sv_818_31;
    double sv_818_35 = sv_818_32 * sv_818_30;
    double sv_818_36 = sv_818_31 * sv_818_31;
    double sv_818_37 = sv_818_32 * sv_818_31;
    double sv_818_38 = sv_818_32 * sv_818_32;
    double sv_818_39 = J0_c2 * J0_c7;
    double sv_818_40 = J0_c8 * sv_818_9;
    double sv_818_41 = sv_818_39 + sv_818_40;
    double sv_818_42 = sv_818_41 / sv_818_17;
    double sv_818_43 = J0_c0 * J0_c8;
    double sv_818_44 = -J0_c2;
    double sv_818_45 = J0_c6 * sv_818_44;
    double sv_818_46 = sv_818_43 + sv_818_45;
    double sv_818_47 = sv_818_46 / sv_818_17;
    double sv_818_48 = J0_c1 * J0_c6;
    double sv_818_49 = J0_c0 * J0_c7;
    double sv_818_50 = -sv_818_49;
    double sv_818_51 = sv_818_48 + sv_818_50;
    double sv_818_52 = sv_818_51 / sv_818_17;
    double sv_818_53 = 0.0001273239544735163 * sv_818_42;
    double sv_818_54 = 0.0001273239544735163 * sv_818_47;
    double sv_818_55 = 0.0001273239544735163 * sv_818_52;
    double sv_818_56 = sv_818_53 / 2;
    double sv_818_57 = sv_818_54 / 2;
    double sv_818_58 = sv_818_55 / 2;
    double sv_818_59 = sv_818_24 / 2;
    double sv_818_60 = sv_818_25 / 2;
    double sv_818_61 = sv_818_26 / 2;
    double sv_818_62 = sv_818_56 * sv_818_56;
    double sv_818_63 = sv_818_56 * sv_818_57;
    double sv_818_64 = sv_818_56 * sv_818_58;
    double sv_818_65 = sv_818_56 * sv_818_59;
    double sv_818_66 = sv_818_56 * sv_818_60;
    double sv_818_67 = sv_818_56 * sv_818_61;
    double sv_818_68 = sv_818_57 * sv_818_57;
    double sv_818_69 = sv_818_57 * sv_818_58;
    double sv_818_70 = sv_818_57 * sv_818_59;
    double sv_818_71 = sv_818_57 * sv_818_60;
    double sv_818_72 = sv_818_57 * sv_818_61;
    double sv_818_73 = sv_818_58 * sv_818_58;
    double sv_818_74 = sv_818_58 * sv_818_59;
    double sv_818_75 = sv_818_58 * sv_818_60;
    double sv_818_76 = sv_818_61 * sv_818_58;
    double sv_818_77 = sv_818_59 * sv_818_59;
    double sv_818_78 = sv_818_59 * sv_818_60;
    double sv_818_79 = sv_818_61 * sv_818_59;
    double sv_818_80 = sv_818_60 * sv_818_60;
    double sv_818_81 = sv_818_61 * sv_818_60;
    double sv_818_82 = sv_818_61 * sv_818_61;
    double sv_818_83 = sv_818_33 + sv_818_62;
    double sv_818_84 = sv_818_34 + sv_818_63;
    double sv_818_85 = sv_818_35 + sv_818_64;
    double sv_818_86 = sv_818_36 + sv_818_68;
    double sv_818_87 = sv_818_37 + sv_818_69;
    double sv_818_88 = sv_818_38 + sv_818_73;
    double sv_818_89 = J0_c1 * J0_c5;
    double sv_818_90 = J0_c2 * J0_c4;
    double sv_818_91 = -sv_818_90;
    double sv_818_92 = sv_818_89 + sv_818_91;
    double sv_818_93 = sv_818_92 / sv_818_17;
    double sv_818_94 = J0_c2 * J0_c3;
    double sv_818_95 = J0_c0 * J0_c5;
    double sv_818_96 = -sv_818_95;
    double sv_818_97 = sv_818_94 + sv_818_96;
    double sv_818_98 = sv_818_97 / sv_818_17;
    double sv_818_99 = J0_c0 * J0_c4;
    double sv_818_100 = J0_c1 * J0_c3;
    double sv_818_101 = -sv_818_100;
    double sv_818_102 = sv_818_99 + sv_818_101;
    double sv_818_103 = sv_818_102 / sv_818_17;
    double sv_818_104 = 0.0001273239544735163 * sv_818_93;
    double sv_818_105 = 0.0001273239544735163 * sv_818_98;
    double sv_818_106 = 0.0001273239544735163 * sv_818_103;
    double sv_818_107 = sv_818_104 / 2;
    double sv_818_108 = sv_818_105 / 2;
    double sv_818_109 = sv_818_106 / 2;
    double sv_818_110 = sv_818_107 * sv_818_107;
    double sv_818_111 = sv_818_107 * sv_818_108;
    double sv_818_112 = sv_818_109 * sv_818_107;
    double sv_818_113 = sv_818_107 * sv_818_59;
    double sv_818_114 = sv_818_107 * sv_818_60;
    double sv_818_115 = sv_818_107 * sv_818_61;
    double sv_818_116 = sv_818_108 * sv_818_108;
    double sv_818_117 = sv_818_109 * sv_818_108;
    double sv_818_118 = sv_818_108 * sv_818_59;
    double sv_818_119 = sv_818_108 * sv_818_60;
    double sv_818_120 = sv_818_108 * sv_818_61;
    double sv_818_121 = sv_818_109 * sv_818_109;
    double sv_818_122 = sv_818_109 * sv_818_59;
    double sv_818_123 = sv_818_109 * sv_818_60;
    double sv_818_124 = sv_818_109 * sv_818_61;
    double sv_818_125 = sv_818_83 + sv_818_110;
    double sv_818_126 = sv_818_84 + sv_818_111;
    double sv_818_127 = sv_818_85 + sv_818_112;
    double sv_818_128 = sv_818_86 + sv_818_116;
    double sv_818_129 = sv_818_87 + sv_818_117;
    double sv_818_130 = sv_818_88 + sv_818_121;
    double sv_818_131 = sv_818_53 + sv_818_53;
    double sv_818_132 = sv_818_54 + sv_818_54;
    double sv_818_133 = sv_818_55 + sv_818_55;
    double sv_818_134 = sv_818_131 / 2;
    double sv_818_135 = sv_818_132 / 2;
    double sv_818_136 = sv_818_133 / 2;
    double sv_818_137 = sv_818_134 * sv_818_134;
    double sv_818_138 = sv_818_134 * sv_818_135;
    double sv_818_139 = sv_818_134 * sv_818_136;
    double sv_818_140 = sv_818_135 * sv_818_135;
    double sv_818_141 = sv_818_135 * sv_818_136;
    double sv_818_142 = sv_818_136 * sv_818_136;
    double sv_818_143 = sv_818_137 + sv_818_77;
    double sv_818_144 = sv_818_138 + sv_818_78;
    double sv_818_145 = sv_818_139 + sv_818_79;
    double sv_818_146 = sv_818_140 + sv_818_80;
    double sv_818_147 = sv_818_141 + sv_818_81;
    double sv_818_148 = sv_818_142 + sv_818_82;
    double sv_818_149 = sv_818_56 * sv_818_107;
    double sv_818_150 = sv_818_57 * sv_818_107;
    double sv_818_151 = sv_818_107 * sv_818_58;
    double sv_818_152 = sv_818_56 * sv_818_108;
    double sv_818_153 = sv_818_57 * sv_818_108;
    double sv_818_154 = sv_818_108 * sv_818_58;
    double sv_818_155 = sv_818_56 * sv_818_109;
    double sv_818_156 = sv_818_57 * sv_818_109;
    double sv_818_157 = sv_818_109 * sv_818_58;
    double sv_818_158 = sv_818_143 + sv_818_110;
    double sv_818_159 = sv_818_144 + sv_818_111;
    double sv_818_160 = sv_818_145 + sv_818_112;
    double sv_818_161 = sv_818_146 + sv_818_116;
    double sv_818_162 = sv_818_147 + sv_818_117;
    double sv_818_163 = sv_818_148 + sv_818_121;
    double sv_818_164 = sv_818_125 + sv_818_62;
    double sv_818_165 = sv_818_126 + sv_818_63;
    double sv_818_166 = sv_818_127 + sv_818_64;
    double sv_818_167 = sv_818_65 + sv_818_65;
    double sv_818_168 = sv_818_66 + sv_818_66;
    double sv_818_169 = sv_818_67 + sv_818_67;
    double sv_818_170 = sv_818_128 + sv_818_68;
    double sv_818_171 = sv_818_129 + sv_818_69;
    double sv_818_172 = sv_818_70 + sv_818_70;
    double sv_818_173 = sv_818_71 + sv_818_71;
    double sv_818_174 = sv_818_72 + sv_818_72;
    double sv_818_175 = sv_818_130 + sv_818_73;
    double sv_818_176 = sv_818_74 + sv_818_74;
    double sv_818_177 = sv_818_75 + sv_818_75;
    double sv_818_178 = sv_818_76 + sv_818_76;
    double sv_818_179 = sv_818_158 + sv_818_77;
    double sv_818_180 = sv_818_159 + sv_818_78;
    double sv_818_181 = sv_818_160 + sv_818_79;
    double sv_818_182 = sv_818_161 + sv_818_80;
    double sv_818_183 = sv_818_162 + sv_818_81;
    double sv_818_184 = sv_818_163 + sv_818_82;
    double sv_818_185 = sv_818_62 + sv_818_77;
    double sv_818_186 = sv_818_63 + sv_818_78;
    double sv_818_187 = sv_818_64 + sv_818_79;
    double sv_818_188 = sv_818_68 + sv_818_80;
    double sv_818_189 = sv_818_69 + sv_818_81;
    double sv_818_190 = sv_818_82 + sv_818_73;
    double sv_818_191 = sv_818_104 + sv_818_104;
    double sv_818_192 = sv_818_105 + sv_818_105;
    double sv_818_193 = sv_818_106 + sv_818_106;
    double sv_818_194 = sv_818_191 / 2;
    double sv_818_195 = sv_818_192 / 2;
    double sv_818_196 = sv_818_193 / 2;
    double sv_818_197 = sv_818_194 * sv_818_194;
    double sv_818_198 = sv_818_194 * sv_818_195;
    double sv_818_199 = sv_818_196 * sv_818_194;
    double sv_818_200 = sv_818_195 * sv_818_195;
    double sv_818_201 = sv_818_196 * sv_818_195;
    double sv_818_202 = sv_818_196 * sv_818_196;
    double sv_818_203 = sv_818_185 + sv_818_197;
    double sv_818_204 = sv_818_186 + sv_818_198;
    double sv_818_205 = sv_818_187 + sv_818_199;
    double sv_818_206 = sv_818_188 + sv_818_200;
    double sv_818_207 = sv_818_189 + sv_818_201;
    double sv_818_208 = sv_818_190 + sv_818_202;
    double sv_818_209 = sv_818_164 + sv_818_110;
    double sv_818_210 = sv_818_165 + sv_818_111;
    double sv_818_211 = sv_818_166 + sv_818_112;
    double sv_818_212 = sv_818_113 + sv_818_113;
    double sv_818_213 = sv_818_114 + sv_818_114;
    double sv_818_214 = sv_818_115 + sv_818_115;
    double sv_818_215 = sv_818_170 + sv_818_116;
    double sv_818_216 = sv_818_171 + sv_818_117;
    double sv_818_217 = sv_818_118 + sv_818_118;
    double sv_818_218 = sv_818_119 + sv_818_119;
    double sv_818_219 = sv_818_120 + sv_818_120;
    double sv_818_220 = sv_818_175 + sv_818_121;
    double sv_818_221 = sv_818_122 + sv_818_122;
    double sv_818_222 = sv_818_123 + sv_818_123;
    double sv_818_223 = sv_818_124 + sv_818_124;
    double sv_818_224 = sv_818_179 + sv_818_110;
    double sv_818_225 = sv_818_180 + sv_818_111;
    double sv_818_226 = sv_818_181 + sv_818_112;
    double sv_818_227 = sv_818_149 + sv_818_149;
    double sv_818_228 = sv_818_150 + sv_818_150;
    double sv_818_229 = sv_818_151 + sv_818_151;
    double sv_818_230 = sv_818_182 + sv_818_116;
    double sv_818_231 = sv_818_183 + sv_818_117;
    double sv_818_232 = sv_818_152 + sv_818_152;
    double sv_818_233 = sv_818_153 + sv_818_153;
    double sv_818_234 = sv_818_154 + sv_818_154;
    double sv_818_235 = sv_818_184 + sv_818_121;
    double sv_818_236 = sv_818_155 + sv_818_155;
    double sv_818_237 = sv_818_156 + sv_818_156;
    double sv_818_238 = sv_818_157 + sv_818_157;
    double sv_818_239 = sv_818_203 + sv_818_185;
    double sv_818_240 = sv_818_204 + sv_818_186;
    double sv_818_241 = sv_818_205 + sv_818_187;
    double sv_818_242 = sv_818_206 + sv_818_188;
    double sv_818_243 = sv_818_207 + sv_818_189;
    double sv_818_244 = sv_818_208 + sv_818_190;
    double sv_818_245 = 24674011002723.39 * sv_818_209;
    double sv_818_246 = 24674011002723.39 * sv_818_210;
    double sv_818_247 = 24674011002723.39 * sv_818_211;
    double sv_818_248 = 24674011002723.39 * sv_818_167;
    double sv_818_249 = 24674011002723.39 * sv_818_168;
    double sv_818_250 = 24674011002723.39 * sv_818_169;
    double sv_818_251 = 24674011002723.39 * sv_818_212;
    double sv_818_252 = 24674011002723.39 * sv_818_213;
    double sv_818_253 = 24674011002723.39 * sv_818_214;
    double sv_818_254 = 24674011002723.39 * sv_818_215;
    double sv_818_255 = 24674011002723.39 * sv_818_216;
    double sv_818_256 = 24674011002723.39 * sv_818_172;
    double sv_818_257 = 24674011002723.39 * sv_818_173;
    double sv_818_258 = 24674011002723.39 * sv_818_174;
    double sv_818_259 = 24674011002723.39 * sv_818_217;
    double sv_818_260 = 24674011002723.39 * sv_818_218;
    double sv_818_261 = 24674011002723.39 * sv_818_219;
    double sv_818_262 = 24674011002723.39 * sv_818_220;
    double sv_818_263 = 24674011002723.39 * sv_818_176;
    double sv_818_264 = 24674011002723.39 * sv_818_177;
    double sv_818_265 = 24674011002723.39 * sv_818_178;
    double sv_818_266 = 24674011002723.39 * sv_818_221;
    double sv_818_267 = 24674011002723.39 * sv_818_222;
    double sv_818_268 = 24674011002723.39 * sv_818_223;
    double sv_818_269 = 24674011002723.39 * sv_818_224;
    double sv_818_270 = 24674011002723.39 * sv_818_225;
    double sv_818_271 = 24674011002723.39 * sv_818_226;
    double sv_818_272 = 24674011002723.39 * sv_818_227;
    double sv_818_273 = 24674011002723.39 * sv_818_228;
    double sv_818_274 = 24674011002723.39 * sv_818_229;
    double sv_818_275 = 24674011002723.39 * sv_818_230;
    double sv_818_276 = 24674011002723.39 * sv_818_231;
    double sv_818_277 = 24674011002723.39 * sv_818_232;
    double sv_818_278 = 24674011002723.39 * sv_818_233;
    double sv_818_279 = 24674011002723.39 * sv_818_234;
    double sv_818_280 = 24674011002723.39 * sv_818_235;
    double sv_818_281 = 24674011002723.39 * sv_818_236;
    double sv_818_282 = 24674011002723.39 * sv_818_237;
    double sv_818_283 = 24674011002723.39 * sv_818_238;
    double sv_818_284 = 24674011002723.39 * sv_818_239;
    double sv_818_285 = 24674011002723.39 * sv_818_240;
    double sv_818_286 = 24674011002723.39 * sv_818_241;
    double sv_818_287 = 24674011002723.39 * sv_818_242;
    double sv_818_288 = 24674011002723.39 * sv_818_243;
    double sv_818_289 = 24674011002723.39 * sv_818_244;
    double sv_818_290 = fabs(sv_818_17);
    double sv_818_291 = sv_818_245 * sv_818_290;
    double sv_818_292 = sv_818_246 * sv_818_290;
    double sv_818_293 = sv_818_247 * sv_818_290;
    double sv_818_294 = sv_818_248 * sv_818_290;
    double sv_818_295 = sv_818_249 * sv_818_290;
    double sv_818_296 = sv_818_250 * sv_818_290;
    double sv_818_297 = sv_818_251 * sv_818_290;
    double sv_818_298 = sv_818_252 * sv_818_290;
    double sv_818_299 = sv_818_253 * sv_818_290;
    double sv_818_300 = sv_818_254 * sv_818_290;
    double sv_818_301 = sv_818_255 * sv_818_290;
    double sv_818_302 = sv_818_256 * sv_818_290;
    double sv_818_303 = sv_818_257 * sv_818_290;
    double sv_818_304 = sv_818_258 * sv_818_290;
    double sv_818_305 = sv_818_259 * sv_818_290;
    double sv_818_306 = sv_818_260 * sv_818_290;
    double sv_818_307 = sv_818_261 * sv_818_290;
    double sv_818_308 = sv_818_262 * sv_818_290;
    double sv_818_309 = sv_818_263 * sv_818_290;
    double sv_818_310 = sv_818_264 * sv_818_290;
    double sv_818_311 = sv_818_265 * sv_818_290;
    double sv_818_312 = sv_818_266 * sv_818_290;
    double sv_818_313 = sv_818_267 * sv_818_290;
    double sv_818_314 = sv_818_268 * sv_818_290;
    double sv_818_315 = sv_818_269 * sv_818_290;
    double sv_818_316 = sv_818_270 * sv_818_290;
    double sv_818_317 = sv_818_271 * sv_818_290;
    double sv_818_318 = sv_818_272 * sv_818_290;
    double sv_818_319 = sv_818_273 * sv_818_290;
    double sv_818_320 = sv_818_274 * sv_818_290;
    double sv_818_321 = sv_818_275 * sv_818_290;
    double sv_818_322 = sv_818_276 * sv_818_290;
    double sv_818_323 = sv_818_277 * sv_818_290;
    double sv_818_324 = sv_818_278 * sv_818_290;
    double sv_818_325 = sv_818_279 * sv_818_290;
    double sv_818_326 = sv_818_280 * sv_818_290;
    double sv_818_327 = sv_818_281 * sv_818_290;
    double sv_818_328 = sv_818_282 * sv_818_290;
    double sv_818_329 = sv_818_283 * sv_818_290;
    double sv_818_330 = sv_818_284 * sv_818_290;
    double sv_818_331 = sv_818_285 * sv_818_290;
    double sv_818_332 = sv_818_286 * sv_818_290;
    double sv_818_333 = sv_818_287 * sv_818_290;
    double sv_818_334 = sv_818_288 * sv_818_290;
    double sv_818_335 = sv_818_289 * sv_818_290;
    fw0 = sv_818_291 * weights_818[iq];
    fw1 = sv_818_292 * weights_818[iq];
    fw2 = sv_818_293 * weights_818[iq];
    fw3 = sv_818_300 * weights_818[iq];
    fw4 = sv_818_301 * weights_818[iq];
    fw5 = sv_818_308 * weights_818[iq];
    fw6 = sv_818_294 * weights_818[iq];
    fw7 = sv_818_295 * weights_818[iq];
    fw8 = sv_818_296 * weights_818[iq];
    fw9 = sv_818_302 * weights_818[iq];
    fw10 = sv_818_303 * weights_818[iq];
    fw11 = sv_818_304 * weights_818[iq];
    fw12 = sv_818_309 * weights_818[iq];
    fw13 = sv_818_310 * weights_818[iq];
    fw14 = sv_818_311 * weights_818[iq];
    fw15 = sv_818_297 * weights_818[iq];
    fw16 = sv_818_298 * weights_818[iq];
    fw17 = sv_818_299 * weights_818[iq];
    fw18 = sv_818_305 * weights_818[iq];
    fw19 = sv_818_306 * weights_818[iq];
    fw20 = sv_818_307 * weights_818[iq];
    fw21 = sv_818_312 * weights_818[iq];
    fw22 = sv_818_313 * weights_818[iq];
    fw23 = sv_818_314 * weights_818[iq];
    fw24 = sv_818_315 * weights_818[iq];
    fw25 = sv_818_316 * weights_818[iq];
    fw26 = sv_818_317 * weights_818[iq];
    fw27 = sv_818_321 * weights_818[iq];
    fw28 = sv_818_322 * weights_818[iq];
    fw29 = sv_818_326 * weights_818[iq];
    fw30 = sv_818_318 * weights_818[iq];
    fw31 = sv_818_319 * weights_818[iq];
    fw32 = sv_818_320 * weights_818[iq];
    fw33 = sv_818_323 * weights_818[iq];
    fw34 = sv_818_324 * weights_818[iq];
    fw35 = sv_818_325 * weights_818[iq];
    fw36 = sv_818_327 * weights_818[iq];
    fw37 = sv_818_328 * weights_818[iq];
    fw38 = sv_818_329 * weights_818[iq];
    fw39 = sv_818_330 * weights_818[iq];
    fw40 = sv_818_331 * weights_818[iq];
    fw41 = sv_818_332 * weights_818[iq];
    fw42 = sv_818_333 * weights_818[iq];
    fw43 = sv_818_334 * weights_818[iq];
    fw44 = sv_818_335 * weights_818[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw25, fw17, fw14, fw37, FE1_C0_D100_Q818, fw19, fw36, fw1, fw20, fw22, fw18, fw12, fw32, fw26, fw44, fw0, fw7, fw42, fw38, fw29, fw4, FE1_C2_D001_Q818, fw15, fw10, fw16, fw5, fw8, fw13, fw23, fw33, fw11, fw35, fw31, fw28, fw30, fw39, fw24, fw41, fw21, fw34, fw3, fw27, fw6, fw43, fw2, fw9, FE1_C1_D010_Q818, fw40
  // Outputs: A
  {
    double temp_0[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_0[j] = fw0 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_1[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_1[j] = fw1 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_2[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_2[j] = fw2 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_3[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_3[j] = fw1 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_4[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_4[j] = fw3 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_5[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_5[j] = fw4 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_6[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_6[j] = fw2 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_7[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_7[j] = fw4 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_8[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_8[j] = fw5 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_9[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_9[j] = fw6 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_10[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_10[j] = fw7 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_11[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_11[j] = fw8 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_12[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_12[j] = fw9 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_13[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_13[j] = fw10 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_14[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_14[j] = fw11 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_15[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_15[j] = fw12 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_16[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_16[j] = fw13 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_17[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_17[j] = fw14 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_18[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_18[j] = fw15 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_19[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_19[j] = fw16 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_20[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_20[j] = fw17 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_21[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_21[j] = fw18 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_22[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_22[j] = fw19 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_23[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_23[j] = fw20 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_24[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_24[j] = fw21 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_25[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_25[j] = fw22 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_26[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_26[j] = fw23 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_27[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_27[j] = fw6 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_28[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_28[j] = fw9 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_29[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_29[j] = fw12 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_30[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_30[j] = fw7 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_31[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_31[j] = fw10 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_32[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_32[j] = fw13 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_33[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_33[j] = fw8 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_34[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_34[j] = fw11 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_35[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_35[j] = fw14 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_36[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_36[j] = fw24 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_37[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_37[j] = fw25 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_38[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_38[j] = fw26 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_39[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_39[j] = fw25 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_40[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_40[j] = fw27 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_41[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_41[j] = fw28 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_42[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_42[j] = fw26 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_43[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_43[j] = fw28 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_44[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_44[j] = fw29 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_45[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_45[j] = fw30 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_46[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_46[j] = fw31 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_47[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_47[j] = fw32 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_48[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_48[j] = fw33 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_49[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_49[j] = fw34 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_50[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_50[j] = fw35 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_51[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_51[j] = fw36 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_52[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_52[j] = fw37 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_53[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_53[j] = fw38 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_54[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_54[j] = fw15 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_55[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_55[j] = fw18 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_56[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_56[j] = fw21 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_57[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_57[j] = fw16 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_58[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_58[j] = fw19 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_59[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_59[j] = fw22 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_60[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_60[j] = fw17 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_61[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_61[j] = fw20 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_62[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_62[j] = fw23 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_63[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_63[j] = fw30 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_64[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_64[j] = fw33 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_65[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_65[j] = fw36 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_66[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_66[j] = fw31 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_67[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_67[j] = fw34 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_68[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_68[j] = fw37 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_69[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_69[j] = fw32 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_70[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_70[j] = fw35 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_71[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_71[j] = fw38 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_72[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_72[j] = fw39 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_73[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_73[j] = fw40 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_74[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_74[j] = fw41 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_75[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_75[j] = fw40 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_76[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_76[j] = fw42 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_77[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_77[j] = fw43 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    double temp_78[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_78[j] = fw41 * FE1_C0_D100_Q818[0][0][iq][j];
    }
    double temp_79[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_79[j] = fw43 * FE1_C1_D010_Q818[0][0][iq][j];
    }
    double temp_80[10] = {0};
    for (int j = 0; j < 10; ++j)
    {
      temp_80[j] = fw44 * FE1_C2_D001_Q818[0][0][iq][j];
    }
    for (int j = 0; j < 10; ++j)
    {
      for (int i = 0; i < 10; ++i)
      {
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_0[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_1[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_2[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_3[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_4[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_5[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_6[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_7[j];
        A[30 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_8[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_9[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_10[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_11[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_12[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_13[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_14[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_15[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_16[j];
        A[30 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_17[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_18[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_19[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_20[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_21[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_22[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_23[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_24[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_25[j];
        A[30 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_26[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_27[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_28[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_29[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_30[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_31[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_32[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_33[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_34[j];
        A[30 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_35[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_36[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_37[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_38[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_39[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_40[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_41[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_42[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_43[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_44[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_45[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_46[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_47[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_48[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_49[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_50[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_51[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_52[j];
        A[30 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_53[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_54[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_55[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_56[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_57[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_58[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_59[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_60[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_61[j];
        A[30 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_62[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_63[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_64[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_65[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_66[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_67[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_68[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_69[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_70[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_71[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_72[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_73[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C0_D100_Q818[0][0][iq][i] * temp_74[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_75[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_76[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q818[0][0][iq][i] * temp_77[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_78[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_79[j];
        A[30 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q818[0][0][iq][i] * temp_80[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(16933917893659141079),
  .domain = 3,
};

// End of code for integral integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron

// Code for form form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e


uint64_t finite_element_hashes_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e[2] = {UINT64_C(16933917893659141079), UINT64_C(16933917893659141079)};
int form_integral_offsets_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e[6] = {0, 1, 1, 1, 1, 1};
static ufcx_integral* form_integrals_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e[1] = {&integral_117952649999bd201ebc1f9815ad37433399dd74_tetrahedron};
int form_integral_ids_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e[1] = {-1};






ufcx_form form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e =
{

  .signature = "8bc024857d627a0b05b41657c565dc03a3f0c03cdf69625df7050454cf965618f8d732523915109085b275a72832640cba9c583d83406ad576c2d6fdb4ef7ea5",
  .rank = 2,

  .num_coefficients = 0,
  .original_coefficient_positions = NULL,
  .coefficient_name_map = NULL,

  .num_constants = 0,
  .constant_ranks = NULL,
  .constant_shapes = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e,

  .form_integrals = form_integrals_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e,
  .form_integral_ids = form_integral_ids_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e,
  .form_integral_offsets = form_integral_offsets_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e
};

// Alias name
ufcx_form* form_libffcx_forms_8085adf0cc1cea66b289b9dd12f9b87033e6af93_0 = &form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e;

// End of code for form form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double const *
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void *
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t *
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t const *
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // _Bool const *
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // _cffi_double_complex_t
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // _cffi_float_complex_t
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const * *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // char const *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int *
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int const * *
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // ufcx_integral * *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufcx_integral *
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 52 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // uint64_t *
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // void(*)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_ridge(unsigned long long *o)
{
  int n = (ridge) <= 0;
  *o = (unsigned long long)((ridge) | 0);  /* check that ridge is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int const * *tmp = &p->constant_ranks; (void)tmp; }
  { int const * * *tmp = &p->constant_shapes; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
  (void)((p->domain) | 0);  /* check that 'ufcx_integral.domain' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e(void)
{
  return &(form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e", (void *)_cffi_var_form_af9209de5b3277649d24ae9d5e3d94fdcdcaa07e, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 48), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ridge", (void *)_cffi_const_ridge, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "constant_ranks", offsetof(ufcx_form, constant_ranks),
                      sizeof(((ufcx_form *)0)->constant_ranks),
                      _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "constant_shapes", offsetof(ufcx_form, constant_shapes),
                       sizeof(((ufcx_form *)0)->constant_shapes),
                       _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 59) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "domain", offsetof(ufcx_integral, domain),
              sizeof(((ufcx_integral *)0)->domain),
              _CFFI_OP(_CFFI_OP_NOOP, 55) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 48, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 13 },
  { "ufcx_integral", 51, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 13, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 52, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet,vertex,ridge" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 48 },
  { "ufcx_integral", 51 },
  { "ufcx_integral_type", 52 },
  { "ufcx_tabulate_tensor_complex128", 0 },
  { "ufcx_tabulate_tensor_complex64", 9 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 18 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  6,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  61,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_8085adf0cc1cea66b289b9dd12f9b87033e6af93(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
    return NULL;
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
     PyInit_libffcx_forms_8085adf0cc1cea66b289b9dd12f9b87033e6af93(void) { return NULL; }
#  endif
#else
PyMODINIT_FUNC
PyInit_libffcx_forms_8085adf0cc1cea66b289b9dd12f9b87033e6af93(void)
{
  return _cffi_init("libffcx_forms_8085adf0cc1cea66b289b9dd12f9b87033e6af93", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
