"""Freeze inspected upstream capabilities and source/API interpretation."""
from pathlib import Path
import json,hashlib,subprocess,sys
R=Path(__file__).resolve().parents[1];W=Path(json.loads((R/'provenance/TASK_PATHS.json').read_text())['work']);initial=json.loads((R/'provenance/INITIAL_SOURCE_IDENTITY.json').read_text());checks=json.loads((R/'validation/MATRIX_AUDIT_SUMMARY.json').read_text())
def save(name,d): (R/name).write_text(json.dumps(d,indent=2)+'\n')
for label,project,env,lic in [('RIGIDMULTIBLOBSWALL','RigidMultiblobsWall','wallref_rmbw','GPL-3.0'),('PYSTOKES','pystokes','wallref_pystokes','MIT')]:
 d=dict(initial[project]);d.update(environment=json.loads((R/'provenance'/(env+'_ENVIRONMENT.json')).read_text()),license=lic,license_file='provenance/'+project+'_LICENSE.txt',license_sha256=hashlib.sha256((R/'provenance'/(project+'_LICENSE.txt')).read_bytes()).hexdigest(),install='PASS',reference_use_only=True,source_directly_integrated_into_production=False,source_archive='provenance/'+project+'_FROZEN_UPSTREAM.tar.gz',source_archive_sha256=hashlib.sha256((R/'provenance'/(project+'_FROZEN_UPSTREAM.tar.gz')).read_bytes()).hexdigest(),submodule_use='NONE_REQUIRED for audited sphere/CPU lubrication path',source_modified=False)
 if project=='pystokes':
  d.update(version='2.3.3',official_short_test='PASS',official_short_test_count=13,official_short_test_log='logs/PYSTOKES_OFFICIAL_SHORT_TEST.log',install_source='unmodified copy of frozen git checkout; local wheel built without source changes',wheel_runtime_scope='CPU Cython extensions; no CUDA')
  p=W/'envs/wallref_pystokes/lib/python3.12/site-packages/pystokes';d['installed_native_extensions']={str(f.relative_to(p)):hashlib.sha256(f.read_bytes()).hexdigest() for f in p.rglob('*.so')}
 else:d.update(reference_implementations=['sphere.sphere_best_mobility_known','Lubrication_Class.ResistCOO_wall'],binding_sha256=hashlib.sha256((W/'build/rmbw/Lubrication_Class.so').read_bytes()).hexdigest(),CPU_build='Unmodified upstream .cc; external compile command and output in provenance',GPU_dependencies_installed=False)
 save(label+'_PROVENANCE.json',d)
base={'repo_commit':initial['RigidMultiblobsWall']['commit'],'license':'GPL-3.0','role':'REFERENCE_ONLY','upstream_modified':False,'sphere_semianalytical':{'function':'sphere/sphere.py:sphere_best_mobility_known','default_sphere_mobility_dispatch':'sphere_mobility calls Swan-Brady low-order blob self mobility; best_mobility is a separately selected function','normal_TT':'Huang rational approximation to Brenner, implemented and useful','parallel_TT':'Goldman near epsilon<0.02979, Faucheux otherwise; direct-SI near branch fails units/positivity','RR_parallel':'162-blob precomputed table + natural cubic spline','RR_normal':'162-blob precomputed table + natural cubic spline','TR_RT':'same precomputed table; full matrix assigns all four couplings equal sign','data_center_height_over_radius':[1.,10.],'data_surface_gap_over_radius':[0.,9.],'extrapolation':'Unprotected cubic extrapolation at epsilon=10,20','issues':['selfMobilityGoldman.py factor_FR=6*pi*a*2 has radius power inconsistent with torque/velocity cross resistance; measured radius collapse fails','sphere.py M[0,4]=M[1,3]=M[3,1]=M[4,0] violates proper 90-degree in-plane rotation covariance','finite blob RR does not supply exact near-contact logarithmic singularity','cubic extrapolation beyond table raises RR_parallel above bulk at epsilon=20'],'matrix_audit':checks['RMBW_SPHERE'],'selected_primary':False},'lubrication':{'entry':'Lubrication/Lubrication_Class.cc:ResistCOO_wall(Sup_if_true=True)','private_mathematics':'WallResistMatrix','outputs':'EXCESS_RESISTANCE_OVER_ISOLATED_BULK','wrapper':'restore original bulk subtraction, solve six basis systems, work-conjugate scale, convert native units to SI','near_modes':{'normal':'Cooley-ONeill asymptotic epsilon<=0.1','tangent':'GCB asymptotic epsilon<=0.01','TR_RT':'GCB + author-fitted linear correction epsilon<=0.1','RR_parallel':'GCB + author-fitted linear correction epsilon<=0.1','RR_normal':'Liu-Prosperetti/Jeffery asymptotic epsilon<=0.01'},'intermediate':'published precomputed 2562-blob coefficient table, linear interpolation; no new multiblob simulation','table_center_height_range':[1.0001,10.018296],'fallback_above_surface_gap':9.018296,'far_fallback':'TT leading 1/z term; TR=RT=0, RR=bulk; high-order rotational/coupling reference unavailable there','regularization':'debye_cut=1e-5, inactive at every tested gap','rotational_excess_clipping':'max(excess rotational diagonal,0), unmodified upstream','COO_threshold':{'native_absolute':1e-12,'reason_dimensionless_native_run':'Direct SI torque entries can fall below fixed cutoff; native inputs vary with radius and viscosity and are scaled independently back to SI'},'matrix_audit':checks['RMBW_LUBRICATION']},'multiblob_role':'No new large blob discretization run; legacy supplied tables consumed by original functions only','single_sphere_role':'drivers/examples, not selected as a new solver','all_supported_modes':['normal_TT','parallel_TT','RR_parallel','RR_normal','TR','RT']}
save('RIGIDMULTIBLOBSWALL_CAPABILITY_AUDIT.json',base)
py={'commit':initial['pystokes']['commit'],'module':'pystokes.wallBounded.Rbm','version':'2.3.3','API_available':['mobilityTT','mobilityTR','mobilityRT','mobilityRR'],'method':'N=1 image-system/self terms, low-order powers of a/z; not lubrication-resummed','passive_no_slip_sphere':'only force/torque APIs called; active-slip propulsion APIs never used','TT_parallel_normalized':'1-9s/16+s^3/8-s^5/16','TT_normal_normalized':'1-9s/8+s^3/2-s^5/8','RR_parallel_normalized':'1-5s^3/16','RR_normal_normalized':'1-s^3/8','s':'a/(a+h)','TR_x_Ty_SI':'-s^4/(64*pi*mu*a^2)','RT_y_Fx_SI':'+s^4/(64*pi*mu*a^2)','TR_y_Tx_SI':'+s^4/(64*pi*mu*a^2)','RT_x_Fy_SI':'-s^4/(64*pi*mu*a^2)','reciprocity_issue':'TR=-RT.T in the nonzero N=1 mixed block, not explainable by one consistent work-conjugate coordinate transform','near_wall_limit':'Mnormal/MT0 ->1/4, Mparallel/MT0 ->1/2; no lubrication divergence','matrix_audit':checks['PYSTOKES'],'capability_vs_validity':'All four APIs execute, but full mobility is not a valid reciprocal resistance reference at this commit','role':'secondary diagonal far-field diagnostic only; no full-matrix endorsement','short_test_scope':'13 official tests PASS; official wall tests check TT expansions, no TR/RT reciprocity assertion','source_changed':False}
save('PYSTOKES_CAPABILITY_AUDIT.json',py)
api={'constructor':'Rbm(radius=a,particles=1,viscosity=mu)','source':'pystokes/wallBounded.pyx','input_arrays':'float64 contiguous length 3*N; [x_1..x_N,y_1..y_N,z_1..z_N]','N1_order':'xyz','outputs':'in-place additive +=; pre-zero output for each impulse','units':'supplied consistently in SI; constructor includes 6*pi*mu*a,8*pi*mu*a^3 scales','signs':'right-handed xyz; source API documents externally applied body force/torque','basis_extraction':'Fx,Fy,Fz,Tx,Ty,Tz each unit separately, all other loads zero','TT':'v += mobilityTT(F)','TR':'v += mobilityTR(T)','RT':'omega += mobilityRT(F)','RR':'omega += mobilityRR(T)','all_matrices_from_API':True,'no_formula_substitution':True,'no_symmetrization':True,'source_line_ranges':{'constructor':[31,37],'TT':[40,159],'TR':[162,237],'RT':[451,527],'RR':[530,612]},'observed_reciprocity':'FAIL; relative=2.0','theory_expected_pattern':'diag(mt,mt,mn,mr,mr,mz), M04=M40=c, M13=M31=-c, others zero','tests_api_evidence':'upstream/tests/test_short.py and raw/PYSTOKES.jsonl'}
save('PYSTOKES_WALL_API_AUDIT.json',api)
print('SOURCE_PROVENANCE_AND_CAPABILITY_SAVED')
