[unix_http_server]
file=/workspace/microbubble_lammps/work/stable_rigid_sphere_near_field_v0_20260916_101617/s.sock
[supervisord]
logfile=/workspace/microbubble_lammps/work/stable_rigid_sphere_near_field_v0_20260916_101617/supervisor.log
pidfile=/workspace/microbubble_lammps/work/stable_rigid_sphere_near_field_v0_20260916_101617/supervisor.pid
childlogdir=/workspace/microbubble_lammps/work/stable_rigid_sphere_near_field_v0_20260916_101617
[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=unix:///workspace/microbubble_lammps/work/stable_rigid_sphere_near_field_v0_20260916_101617/s.sock
[program:initial]
command=/workspace/microbubble_lammps/work/palabos_lammps_coupling_v0_20260915_224019/venv/bin/python -B /workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/scripts/run_phase.py initial
directory=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/logs/PHASE_INITIAL.log
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:initial_resume]
command=/workspace/microbubble_lammps/work/palabos_lammps_coupling_v0_20260915_224019/venv/bin/python -B /workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/scripts/run_phase.py initial_resume
directory=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/logs/PHASE_INITIAL_RESUME.log
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:remaining]
command=/workspace/microbubble_lammps/work/palabos_lammps_coupling_v0_20260915_224019/venv/bin/python -B /workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/scripts/run_phase.py remaining
directory=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/workspace/microbubble_lammps/results/stable_rigid_sphere_near_field_v0_20260916_101617/logs/PHASE_REMAINING.log
redirect_stderr=true
stdout_logfile_maxbytes=0
