from pathlib import Path
import json,hashlib,csv
C=Path(__file__).resolve().parent;G=C/'geometry';fit=json.loads((G/'RBC_GEOMETRY_FIT_AUDIT.json').read_text());meta=json.loads((G/'NATIVE_MESH_GENERATION.json').read_text())
H=Path('/home/lzy/projects/hemocell_starter');V=H/'test_code/step3c_inlet_calibration/inletCalibrationMPI.cpp'
def sha(p):return hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
wall=dict(status='ABSENT',scope='Current production Guo vascular setup; not a claim that HemoCell library lacks a wall-repulsion API',library_api_present=True,library_entry='HemoCell::enableBoundaryParticles',vascular_enable_call_present='enableBoundaryParticles(' in V.read_text(),default_boundaryRepulsionEnabled=False,particle_site_rule='HemoCellParticleField::populateBoundaryParticles selects dynamics.isBoundary() nodes adjacent to non-boundary nodes',vascular_dynamics=['BGKdynamics','NoDynamics'],Guo_boundary='OffLatticeBoundaryCondition3D inserted processors; no isBoundary site dynamics or explicit RBC wall force',not_equivalent_to_fluid_no_slip=True,force_constant_or_cutoff_invented=False,CASE_B='BLOCKED_WALL_INTERACTION_IMPLEMENTATION',source_evidence={str(p.relative_to(H)):sha(p) for p in [V,H/'hemocell.h',H/'core/hemoCell.cpp',H/'core/hemoCellParticleField.cpp',H/'core/hemoCellFields.cpp',H/'palabos/src/core/dynamics.hh']})
assert wall['vascular_enable_call_present'] is False
(C/'WALL_INTERACTION_AUDIT.json').write_text(json.dumps(wall,indent=2)+'\n')
contract=dict(schema='RBC_ONLY_VALIDATION_STAGE_1_CURRENT_PRODUCTION_V1',stage_status='STOPPED_AT_GEOMETRY_HARD_GATE',frozen_before_any_coupled_solver=True,stage_order=['BUILD','GEOMETRY_FIT','MPI1_SANITY','CASE_A','CASE_B','CASE_C'],medium_contract='contracts/NEW_MEDIUM_NUMERICS_CONTRACT.json',medium_status='SUSPENDING_MEDIUM_NUMERICS_PASS_FROM_PRECEDING_SMOKE',prepare_numerics_single_source=True,medium_physical_parameters_tuned=False,model=dict(name='MOUSE_RBC_DEV_V0',shape='RBC_FROM_SPHERE',target_volume_um3=50,nominal_scale=meta['scale'],radius_m=meta['radius_m'],effective_diameter_um=2*meta['radius_m']*1e6,actual_discrete_volume_um3=fit['mesh']['actual_volume_um3'],target_volume_reproduction='FAIL_FIXED_NOMINAL_SCALE_DISCRETE_VOLUME_DIFFERS',mechanics='RbcHighOrderModel',kLink=15,kArea=5,kBend=80,kVolume=20,minNumTriangles=600,actual_triangles=1280,actual_vertices=642,interior_viscosity=False,geometry_changed_after_fit=False,mechanics_runtime_validation='NOT_RUN'),gates=dict(max_relative_volume_error=.05,max_relative_area_error=.05,relative_errors_reference='Initial actual closed native mesh; separately disclose 50um3 nominal target mismatch',finite_RBC_checks='positions, velocities, forces every timestep, no per-step file output',wall_penetration_metric='negative of frozen closed-STL signed distance, independently verified using solid-angle winding plus nearest-triangle distance',wall_penetration_tolerance_lu=0.,wall_metric_validation_scope='STATIC_GEOMETRY_ONLY; runtime not executed',triangle_inversion_definition='UNVERIFIED_NOT_IMPLEMENTED_BECAUSE_PRECEDING_GEOMETRY_HARD_GATE_FAILED',force_velocity_runaway_gate='PENDING_NO_FORMAL_CASE_AUTHORIZED_AFTER_FAILED_GEOMETRY_GATE',fluid_rho_limits=[.99,1.01],fluid_Mach_hard_limit=.05,fluid_Mach_smoke_limit=.01,outlet_transient_backflow_is_failure=False,inlet_accuracy_gate=False),monitor_schedule=dict(RBC_finite=1,RBC_geometry=10,fluid_safety=50,compact_case_CSV_and_stdout=100),output_policy=dict(fluid=['initial','final','failure'],RBC_mesh=['initial','mid','final','failure'],checkpoint=False,limit_bytes=2**30),cases={
'MPI1_SANITY':dict(planned_max_steps=200,MPI_ranks=1,RBC_count=1,positions=None,orientations=None,status='NOT_RUN_GEOMETRY_GATE_FAILED',actual_steps=0),
'CASE_A':dict(planned_max_steps=2000,MPI_ranks=4,RBC_count=1,positions=None,orientations=None,status='NOT_RUN_GEOMETRY_GATE_FAILED',actual_steps=0),
'CASE_B':dict(planned_max_steps=2000,MPI_ranks=4,RBC_count=1,positions=None,orientations=None,status='BLOCKED_WALL_INTERACTION_IMPLEMENTATION',also_blocked_by='GEOMETRY_GATE_FAILED',actual_steps=0),
'CASE_C':dict(planned_max_steps=5000,MPI_ranks=4,allowed_RBC_counts=[2,3,4],RBC_count=None,positions=None,orientations=None,status='NOT_RUN_GEOMETRY_GATE_FAILED',actual_steps=0)},spawn_policy='No safe pose accepted; null positions are intentional and prohibit solver launch. Best diagnostic pose is explicitly NOT an authorized spawn.',random_orientation=False,random_seed=None,search_policy_sha256=sha(C/'GEOMETRY_SEARCH_POLICY.json'),native_mesh_sha256={p.name:sha(p) for p in [G/'RBC_REFERENCE_VERTICES.csv',G/'RBC_REFERENCE_TRIANGLES.csv']},HUMAN_RBC_REVIEW='PENDING',SMALL_PACK_IS_NOT_HCT_VALIDATION=True,RBC_GPU_CORRECTNESS='PENDING',MICROBUBBLE='OFF',ADHESION='OFF',ULTRASOUND='OFF',next_step='USER_REVIEW_BEFORE_RBC_STAGE2')
(C/'RBC_STAGE1_CONTRACT.json').write_text(json.dumps(contract,indent=2)+'\n')
for case,data in contract['cases'].items():
 d=C/case;d.mkdir(exist_ok=True);(d/'CASE_STATUS.json').write_text(json.dumps(data,indent=2)+'\n');(d/'README.md').write_text('未执行耦合求解器。几何硬门失败，禁止使用最佳诊断姿态作为 spawn。\n')
with (C/'RBC_STAGE1_METRICS.csv').open('w',newline='') as f:
 writer=csv.DictWriter(f,fieldnames=['scope','case','status','actual_steps','particle_count_created','reference_mesh_volume_um3','reference_mesh_area_um2','nominal_target_volume_um3','reference_mesh_target_relative_difference','best_diagnostic_wall_clearance_um','best_diagnostic_outside_vertices']);writer.writeheader();writer.writerow(dict(scope='STATIC_REFERENCE_MESH_ONLY_NOT_RUNTIME',case='GEOMETRY_FIT',status='FAIL',actual_steps=0,particle_count_created=0,reference_mesh_volume_um3=fit['mesh']['actual_volume_um3'],reference_mesh_area_um2=fit['mesh']['actual_area_um2'],nominal_target_volume_um3=50,reference_mesh_target_relative_difference=fit['mesh']['actual_volume_um3']/50-1,best_diagnostic_wall_clearance_um=fit['best_pose']['min_distance']*meta['dx_m']*1e6,best_diagnostic_outside_vertices=fit['best_pose']['outside_vertices']))
(C/'RBC_STAGE1_CONTRACT.json').chmod(0o444)
print('CONTRACT_AND_BLOCKED_CASES_RECORDED')
