"""Exact SWC subsets and full-source VTP metadata for independent inspection."""
import csv
import json
from pathlib import Path

import numpy as np
import pyvista as pv

from .mevo_graph import ROLE_CODES, graph_counts, load_exact_graph
from .roi_landmarks import ROI_DEFINITIONS
from .swc_export import read_source, write_swc
from .vascularmd_adapter import COMMIT


def write_json(path, value):
    with Path(path).open("x", encoding="utf-8") as stream:
        json.dump(value, stream, indent=2, ensure_ascii=False, allow_nan=False)
        stream.write("\n")


def write_csv(path, rows):
    with Path(path).open("x", newline="", encoding="utf-8") as stream:
        if rows:
            writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)


def export_roi(path, graph, exact, roi_name, roi, source_hash, anatomical_status,
               *, context_nodes=frozenset()):
    headers = ["BraVa MeVO ROI extraction", f"Source: {exact.source.path.name}",
        f"Source SHA256: {source_hash}", f"ROI: {roi_name}", f"Territory: {roi['territory']}",
        f"Side: {roi['side']}", f"Included anatomical segments: {','.join(roi['segments'])}",
        "Landmark method: manual/landmark-assisted", f"ANATOMICAL_STATUS = {anatomical_status}",
        f"Anatomical verification: {anatomical_status}", "Original coordinates preserved",
        "Original radii preserved", "Radius column is radius, not diameter", "Original SWC preserved",
        f"Contains proximal modeling context: {'YES' if context_nodes else 'NO'}",
        f"Context node count: {len(context_nodes)}", "Generated by tools/vascularmd_extract_mevo.py"]
    mapping = write_swc(path, graph, exact.source.path, COMMIT, "exact-node-subset", header_lines=headers)
    saved = read_source(path)
    if set(saved.graph.edges) != {(mapping[a], mapping[b]) for a, b in graph.edges}:
        raise ValueError("Extracted SWC round-trip changed directed connectivity")
    rows = []
    for original, output in mapping.items():
        data = exact.graph.nodes[original]
        np.testing.assert_array_equal(data["coords"], saved.graph.nodes[output]["coords"])
        if data["swc_type"] != saved.graph.nodes[output]["swc_type"]:
            raise ValueError("Original SWC TYPE was not retained")
        parent = next(graph.predecessors(original), None)
        x, y, z, r = map(float, data["coords"])
        rows.append({"roi_node_id": output, "original_swc_id": original,
            "original_parent_id": next(exact.graph.predecessors(original), -1),
            "roi_parent_id": mapping[parent] if parent is not None else -1, "swc_type": data["swc_type"],
            "x": x, "y": y, "z": z, "radius": r,
            "is_proximal_boundary": original in roi["proximal_nodes"],
            "is_distal_boundary": original in roi["distal_nodes"],
            "is_context": original in context_nodes, "is_anatomical_roi": original not in context_nodes,
            "roi_name": roi_name})
    mapping_path = path.with_name(path.stem + "_node_mapping.csv")
    write_csv(mapping_path, rows)
    native = load_exact_graph(path)
    root = next(n for n in native.graph if native.graph.in_degree(n) == 0)
    can_model = native.native_valid and native.graph.out_degree(root) == 1
    return {"swc": path.name, "node_mapping": mapping_path.name,
            "max_xyz_difference_for_mapped_nodes": 0.0, "max_radius_difference_for_mapped_nodes": 0.0,
            "swc_types_preserved": True, "round_trip_topology_preserved": True,
            "vascularmd_reload": {"check_full_graph": native.native_valid,
                "root_out_degree": native.graph.out_degree(root), "compatible_with_modeling_adapter": can_model,
                "reason": None if can_model else "Native modeling adapter needs a single nonbranching inlet; consider upstream-edge context"}}


def source_polydata(exact, roi_data=()):
    """One point per original node; memberships remain explicit even if ROIs overlap."""
    graph = exact.graph
    ids = list(graph)
    indexes = {node: i for i, node in enumerate(ids)}
    edges = list(graph.edges)
    points = np.asarray([graph.nodes[n]["coords"] for n in ids])
    cells = np.asarray([[2, indexes[a], indexes[b]] for a, b in edges], dtype=np.int64).ravel()
    mesh = pv.PolyData(points[:, :3], lines=cells)
    mesh.point_data["original_swc_id"] = ids
    mesh.point_data["swc_type"] = [graph.nodes[n]["swc_type"] for n in ids]
    mesh.point_data["radius"] = points[:, 3]
    mesh.point_data["diameter"] = points[:, 3] * 2
    for key in ("topo_node_id", "topology_type_code", "topo_edge_start", "topo_edge_end", "topo_edge_offset", "component_id"):
        mesh.point_data[key] = [exact.locations[n][key] for n in ids]
    mesh.point_data["in_degree"] = [graph.in_degree(n) for n in ids]
    mesh.point_data["out_degree"] = [graph.out_degree(n) for n in ids]
    names = list(ROI_DEFINITIONS)
    for data, length in ((mesh.point_data, len(ids)), (mesh.cell_data, len(edges))):
        for key in ("roi_id", "roi_name_code", "roi_membership_bits", "is_roi", "is_context", "is_boundary", "boundary_type"):
            data[key] = np.zeros(length, dtype=np.int32)
    for name, roi, result in roi_data:
        code = names.index(name) + 1
        membership = np.array([n in result.graph for n in ids], dtype=np.int32)
        context = np.array([n in result.context_nodes for n in ids], dtype=np.int32)
        boundary = np.array([1 if n in roi["proximal_nodes"] else 2 if n in roi["distal_nodes"] else
                             3 if n in roi["exclude_subtree_roots"] else 0 for n in ids], dtype=np.int32)
        edge_membership = np.array([result.graph.has_edge(a, b) for a, b in edges], dtype=np.int32)
        edge_context = np.array([bool((a in result.context_nodes or b in result.context_nodes) and
                    result.modelable_graph is not None and result.modelable_graph.has_edge(a, b)) for a, b in edges], dtype=np.int32)
        edge_boundary = np.array([boundary[indexes[b]] or boundary[indexes[a]] for a, b in edges], dtype=np.int32)
        for target, flags, ctx, bd in ((mesh.point_data, membership, context, boundary),
                                       (mesh.cell_data, edge_membership, edge_context, edge_boundary)):
            target[name + "_is_roi"] = flags
            target[name + "_is_context"] = ctx
            target[name + "_boundary_type"] = bd
            target["roi_id"] = np.where(flags, np.where(target["roi_id"] == 0, code, -1), target["roi_id"])
            target["roi_name_code"] = target["roi_id"]
            target["roi_membership_bits"] |= flags * (1 << (code - 1))
            target["is_roi"] |= flags
            target["is_context"] |= ctx
            target["is_boundary"] |= (bd != 0).astype(np.int32)
            target["boundary_type"] = np.where(bd, np.where((target["boundary_type"] == 0) | (target["boundary_type"] == bd), bd, -1), target["boundary_type"])
    mesh.cell_data["original_swc_id"] = [b for a, b in edges]
    mesh.cell_data["original_parent_id"] = [a for a, b in edges]
    mesh.cell_data["radius"] = [graph.nodes[b]["coords"][3] for a, b in edges]
    mesh.cell_data["diameter"] = 2 * mesh.cell_data["radius"]
    mesh.field_data["roi_names_by_code_1_to_6"] = names
    mesh.field_data["topology_role_codes"] = [f"{v}={k}" for k, v in ROLE_CODES.items()]
    mesh.field_data["boundary_codes"] = ["0=none; 1=proximal; 2=distal; 3=excluded; -1=multiple (see per-ROI arrays)"]
    mesh.field_data["roi_id_note"] = ["0=outside; -1=overlap; positive=ROI code. Bit mask and per-ROI arrays retain all memberships."]
    return mesh
