# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /usr/bin/mpicxx.openmpi
CXX_DEFINES = -DCOMPILING_HEMOCELL_LIBRARY -DPLB_MPI_PARALLEL -DPLB_SMP_PARALLEL -DPLB_USE_POSIX

CXX_INCLUDES = -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/config -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/core -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/helper -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/io -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/mechanics -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/external/tinyxml2 -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/./palabos/src -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/./palabos/externalLibraries/tinyxml -I/home/lzy/projects/hemocell_starter/vendor/HemoCell -I/home/lzy/projects/hemocell_starter/vendor/HemoCell/./palabos/externalLibraries -I/usr/include/hdf5/openmpi

CXX_FLAGS =  -O3 -march=native -std=c++11 -ggdb -Wformat -Wformat-security -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused-parameter -Wall -Wextra -Werror=format-security -Wno-empty-body -Wno-unused-result -Wno-ignored-qualifiers -O3 -DNDEBUG

