#include "frozen_flow.hpp"
#include <hdf5.h>
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <limits>
namespace frozen {
static void require(bool x,const char* msg){if(!x)throw std::runtime_error(msg);}
static std::string attr(hid_t f,const char* name){hid_t a=H5Aopen(f,name,H5P_DEFAULT);require(a>=0,"Missing HDF5 attribute");hid_t t=H5Aget_type(a);std::string value;if(H5Tis_variable_str(t)){char* s=nullptr;require(H5Aread(a,t,&s)>=0,"Attribute read failed");value=s;H5free_memory(s);}else{std::vector<char>s(H5Tget_size(t)+1,0);require(H5Aread(a,t,s.data())>=0,"Attribute read failed");value=s.data();}H5Tclose(t);H5Aclose(a);return value;}
template<typename T>static std::vector<T> dataset(hid_t f,const char* name,hid_t type,int rank,hsize_t width=0){hid_t d=H5Dopen2(f,name,H5P_DEFAULT);require(d>=0,"Missing dataset");hid_t sp=H5Dget_space(d);require(H5Sget_simple_extent_ndims(sp)==rank,"Dataset rank mismatch");hsize_t shape[2]={1,1};H5Sget_simple_extent_dims(sp,shape,nullptr);if(width)require(shape[1]==width,"Dataset width mismatch");hsize_t n=H5Sget_simple_extent_npoints(sp);std::vector<T> v(n);require(H5Dread(d,type,H5S_ALL,H5S_ALL,H5P_DEFAULT,v.data())>=0,"Dataset read failed");H5Sclose(sp);H5Dclose(d);return v;}
FlowField::FlowField(const std::string& path){hid_t f=H5Fopen(path.c_str(),H5F_ACC_RDONLY,H5P_DEFAULT);require(f>=0,"Cannot open frozen HDF5 field");try{require(attr(f,"format_version")=="FROZEN_FLOW_FIELD_V0","Wrong field version");require(attr(f,"coordinate_units")=="m"&&attr(f,"velocity_units")=="m/s","Wrong field units");auto dim=dataset<int64_t>(f,"dims",H5T_NATIVE_INT64,1);auto org=dataset<double>(f,"origin_m",H5T_NATIVE_DOUBLE,1);auto delta=dataset<double>(f,"dx_m",H5T_NATIVE_DOUBLE,0);require(dim.size()==3&&org.size()==3&&delta.size()==1,"Bad grid metadata");std::copy(dim.begin(),dim.end(),dims.begin());std::copy(org.begin(),org.end(),origin.begin());dx=delta[0];indices=dataset<uint64_t>(f,"linear_index",H5T_NATIVE_UINT64,1);fluid_indices=dataset<uint64_t>(f,"fluid_linear_index",H5T_NATIVE_UINT64,1);velocity=dataset<double>(f,"Velocity_m_s",H5T_NATIVE_DOUBLE,2,3);H5Fclose(f);}catch(...){H5Fclose(f);throw;}
 require(std::isfinite(dx)&&dx>0,"Invalid dx");uint64_t count=1;for(int a=0;a<3;++a){require(dims[a]>=2&&std::isfinite(origin[a]),"Invalid grid");count*=dims[a];}require(!indices.empty()&&!fluid_indices.empty()&&velocity.size()==3*indices.size(),"Bad velocity size");auto ordered=[](const std::vector<uint64_t>& v){return std::adjacent_find(v.begin(),v.end(),std::greater_equal<uint64_t>())==v.end();};require(ordered(indices)&&ordered(fluid_indices),"Indices not sorted and unique");require(indices.back()<count&&fluid_indices.back()<count,"Index outside grid");for(auto id:indices)require(std::binary_search(fluid_indices.begin(),fluid_indices.end(),id),"Velocity on non-fluid node");for(double v:velocity)require(std::isfinite(v),"Nonfinite field velocity");}
Status FlowField::node(uint64_t id,size_t& slot)const{if(!std::binary_search(fluid_indices.begin(),fluid_indices.end(),id))return Status::SOLID;auto it=std::lower_bound(indices.begin(),indices.end(),id);if(it==indices.end()||*it!=id)return Status::MISSING;slot=size_t(it-indices.begin());return Status::VALID;}
Query FlowFieldSampler::query(Vec x)const{Vec q,frac;std::array<int64_t,3> base;for(int a=0;a<3;++a){if(!std::isfinite(x[a]))return{Status::NONFINITE_POSITION,{0,0,0}};q[a]=(x[a]-field.origin[a])/field.dx;if(!(q[a]>=0&&q[a]<double(field.dims[a]-1)))return{Status::OUTSIDE,{0,0,0}};base[a]=int64_t(std::floor(q[a]));frac[a]=q[a]-base[a];}Vec out={0,0,0};for(int z=0;z<2;++z)for(int y=0;y<2;++y)for(int xbit=0;xbit<2;++xbit){uint64_t id=(base[0]+xbit)+field.dims[0]*((base[1]+y)+field.dims[1]*(base[2]+z));size_t slot=0;auto status=field.node(id,slot);if(status!=Status::VALID)return{status,{0,0,0}};double weight=(xbit?frac[0]:1-frac[0])*(y?frac[1]:1-frac[1])*(z?frac[2]:1-frac[2]);for(int a=0;a<3;++a)out[a]+=weight*field.velocity[3*slot+a];}return{Status::VALID,out};}
Vec TechnicalStokesDrag::force(double mu,double d,Vec uf,Vec vp){require(mu>0&&std::isfinite(mu)&&d>0&&std::isfinite(d),"Invalid Stokes inputs");double gamma=3*std::acos(-1.0)*mu*d;Vec f;for(int a=0;a<3;++a){require(std::isfinite(uf[a])&&std::isfinite(vp[a]),"Nonfinite Stokes velocity");f[a]=gamma*(uf[a]-vp[a]);require(std::isfinite(f[a]),"Nonfinite Stokes force");}return f;}
}
