version: 1
source:
  path: ../../vessel_model/T - Brava/swc_files/BG001.CNG.swc
  filename: BG001.CNG.swc
  sha256: 5b69c6c406e4724ffc15a2a4c6b5958cbb169b822a05098d6ebedeecbbb3afbe
  subject_id: BG001
  units: mm
annotation_date: '2026-09-24T17:46:33.308760+00:00'
annotator: ''
rois:
  LMCA_M2M3:
    enabled: false
    side: L
    territory: MCA
    segments:
    - M2
    - M3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
  RMCA_M2M3:
    enabled: false
    side: R
    territory: MCA
    segments:
    - M2
    - M3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
  LACA_A2A3:
    enabled: false
    side: L
    territory: ACA
    segments:
    - A2
    - A3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
  RACA_A2A3:
    enabled: false
    side: R
    territory: ACA
    segments:
    - A2
    - A3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
  LPCA_P2P3:
    enabled: false
    side: L
    territory: PCA
    segments:
    - P2
    - P3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
  RPCA_P2P3:
    enabled: false
    side: R
    territory: PCA
    segments:
    - P2
    - P3
    proximal_nodes: []
    distal_nodes: []
    exclude_subtree_roots: []
    proximal_boundary_status: unknown
    manually_verified: false
    notes: ''
    internal_landmarks: {}
